#### Import pandas library using alias pd.

In [1]:
import pandas

#### Load file recipes.csv from the data subfolder and store it in a variable df. Use the first column as index.

In [3]:
df = pandas.read_csv("data/recipes.csv", index_col=0)
df

,vegetarian,glutenFree,dairyFree,veryHealthy,healthScore,aggregateLikes,id,title,pricePerServing,readyInMinutes,...,VitaminB3Amount,VitaminB3percentOfDailyNeed,VitaminB1Amount,VitaminB1percentOfDailyNeed,CalciumAmount,CalciumpercentOfDailyNeed,AlcoholAmount,AlcoholpercentOfDailyNeed,CaffeineAmount,CaffeinepercentOfDailyNeed
0,True,True,True,False,1.0,3,633998,Banana Blueberry Pancakes,55.79,45,...,0.49,2.44,0.03,2.26,18.11,1.81,NaN,NaN,NaN,NaN
1,True,True,False,False,0.0,1,634426,Basil and Orange Confit Compound Butter,15.07,45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,False,False,False,False,3.0,1,635085,Black Bottom Banana Bars,78.85,45,...,2.63,13.13,0.32,21.09,100.80,10.08,0.28,1.53,9.89,3.30
3,True,False,True,False,2.0,1,663229,The Best Raw Chocolate Chip Cookies,54.64,45,...,0.65,3.26,0.10,6.47,26.79,2.68,NaN,NaN,NaN,NaN
4,False,True,False,False,31.0,3,651437,Mediterranean Spinach Artichoke Dip,115.26,45,...,0.66,3.29,0.07,4.64,162.84,16.28,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,False,True,True,False,18.0,13,638315,"Chicken Sausage, White Bean and Cabbage Soup",196.23,45,...,0.53,2.67,0.15,10.23,102.67,10.27,NaN,NaN,NaN,NaN
146,True,False,False,False,1.0,2,656248,Pinot Noir Brownies,65.76,45,...,0.21,1.07,0.03,1.68,19.82,1.98,2.48,13.76,10.69,3.56
147,True,True,True,True,93.0,2,637297,Cauliflower Chickpea Stew,139.28,45,...,4.77,23.83,0.45,29.70,141.16,14.12,NaN,NaN,NaN,NaN
148,True,True,False,False,5.0,1,659412,Saut√©ed Balsamic Green Beans With Cherry Tomatoes,101.81,45,...,1.15,5.73,0.12,7.85,55.64,5.56,NaN,NaN,NaN,NaN
149,True,True,True,True,100.0,4,647875,Indian-Style Dill and Turmeric Potato Salad,117.24,30,...,0.21,1.05,NaN,NaN,27.96,2.80,NaN,NaN,NaN,NaN

#### Print the type of variable df.

In [4]:
type(df)

pandas.core.frame.DataFrame

#### Print the number of columns and number of rows of the df DataFrame.

In [5]:
df.shape

(150, 78)

#### What are the names of the columns in df?

In [6]:
df.columns

Index(['vegetarian', 'glutenFree', 'dairyFree', 'veryHealthy', 'healthScore',
       'aggregateLikes', 'id', 'title', 'pricePerServing', 'readyInMinutes',
       'servings', 'sourceUrl', 'CaloriesAmount', 'CaloriespercentOfDailyNeed',
       'FatAmount', 'FatpercentOfDailyNeed', 'SaturatedFatAmount',
       'SaturatedFatpercentOfDailyNeed', 'CarbohydratesAmount',
       'CarbohydratespercentOfDailyNeed', 'NetCarbohydratesAmount',
       'NetCarbohydratespercentOfDailyNeed', 'SugarAmount',
       'SugarpercentOfDailyNeed', 'CholesterolAmount',
       'CholesterolpercentOfDailyNeed', 'SodiumAmount',
       'SodiumpercentOfDailyNeed', 'ProteinAmount',
       'ProteinpercentOfDailyNeed', 'FiberAmount', 'FiberpercentOfDailyNeed',
       'VitaminB6Amount', 'VitaminB6percentOfDailyNeed', 'ManganeseAmount',
       'ManganesepercentOfDailyNeed', 'SeleniumAmount',
       'SeleniumpercentOfDailyNeed', 'PotassiumAmount',
       'PotassiumpercentOfDailyNeed', 'VitaminB2Amount',
       'VitaminB2percentOfDailyNeed', 'VitaminCAmount',
       'VitaminCpercentOfDailyNeed', 'PhosphorusAmount',
       'PhosphoruspercentOfDailyNeed', 'FolateAmount',
       'FolatepercentOfDailyNeed', 'VitaminB5Amount',
       'VitaminB5percentOfDailyNeed', 'MagnesiumAmount',
       'MagnesiumpercentOfDailyNeed', 'IronAmount', 'IronpercentOfDailyNeed',
       'VitaminKAmount', 'VitaminKpercentOfDailyNeed', 'CopperAmount',
       'CopperpercentOfDailyNeed', 'VitaminAAmount',
       'VitaminApercentOfDailyNeed', 'VitaminB12Amount',
       'VitaminB12percentOfDailyNeed', 'VitaminDAmount',
       'VitaminDpercentOfDailyNeed', 'ZincAmount', 'ZincpercentOfDailyNeed',
       'VitaminEAmount', 'VitaminEpercentOfDailyNeed', 'VitaminB3Amount',
       'VitaminB3percentOfDailyNeed', 'VitaminB1Amount',
       'VitaminB1percentOfDailyNeed', 'CalciumAmount',
       'CalciumpercentOfDailyNeed', 'AlcoholAmount',
       'AlcoholpercentOfDailyNeed', 'CaffeineAmount',
       'CaffeinepercentOfDailyNeed'],
      dtype='object')

#### Rename column id to RecipeId. Drop column "veryHealthy".

In [7]:
df = df.rename(columns={'id': 'RecipeId'})
df

,vegetarian,glutenFree,dairyFree,veryHealthy,healthScore,aggregateLikes,RecipeId,title,pricePerServing,readyInMinutes,...,VitaminB3Amount,VitaminB3percentOfDailyNeed,VitaminB1Amount,VitaminB1percentOfDailyNeed,CalciumAmount,CalciumpercentOfDailyNeed,AlcoholAmount,AlcoholpercentOfDailyNeed,CaffeineAmount,CaffeinepercentOfDailyNeed
0,True,True,True,False,1.0,3,633998,Banana Blueberry Pancakes,55.79,45,...,0.49,2.44,0.03,2.26,18.11,1.81,NaN,NaN,NaN,NaN
1,True,True,False,False,0.0,1,634426,Basil and Orange Confit Compound Butter,15.07,45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,False,False,False,False,3.0,1,635085,Black Bottom Banana Bars,78.85,45,...,2.63,13.13,0.32,21.09,100.80,10.08,0.28,1.53,9.89,3.30
3,True,False,True,False,2.0,1,663229,The Best Raw Chocolate Chip Cookies,54.64,45,...,0.65,3.26,0.10,6.47,26.79,2.68,NaN,NaN,NaN,NaN
4,False,True,False,False,31.0,3,651437,Mediterranean Spinach Artichoke Dip,115.26,45,...,0.66,3.29,0.07,4.64,162.84,16.28,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,False,True,True,False,18.0,13,638315,"Chicken Sausage, White Bean and Cabbage Soup",196.23,45,...,0.53,2.67,0.15,10.23,102.67,10.27,NaN,NaN,NaN,NaN
146,True,False,False,False,1.0,2,656248,Pinot Noir Brownies,65.76,45,...,0.21,1.07,0.03,1.68,19.82,1.98,2.48,13.76,10.69,3.56
147,True,True,True,True,93.0,2,637297,Cauliflower Chickpea Stew,139.28,45,...,4.77,23.83,0.45,29.70,141.16,14.12,NaN,NaN,NaN,NaN
148,True,True,False,False,5.0,1,659412,Saut√©ed Balsamic Green Beans With Cherry Tomatoes,101.81,45,...,1.15,5.73,0.12,7.85,55.64,5.56,NaN,NaN,NaN,NaN
149,True,True,True,True,100.0,4,647875,Indian-Style Dill and Turmeric Potato Salad,117.24,30,...,0.21,1.05,NaN,NaN,27.96,2.80,NaN,NaN,NaN,NaN

In [8]:
df = df.drop('veryHealthy', axis=1)
df

,vegetarian,glutenFree,dairyFree,healthScore,aggregateLikes,RecipeId,title,pricePerServing,readyInMinutes,servings,...,VitaminB3Amount,VitaminB3percentOfDailyNeed,VitaminB1Amount,VitaminB1percentOfDailyNeed,CalciumAmount,CalciumpercentOfDailyNeed,AlcoholAmount,AlcoholpercentOfDailyNeed,CaffeineAmount,CaffeinepercentOfDailyNeed
0,True,True,True,1.0,3,633998,Banana Blueberry Pancakes,55.79,45,8,...,0.49,2.44,0.03,2.26,18.11,1.81,NaN,NaN,NaN,NaN
1,True,True,False,0.0,1,634426,Basil and Orange Confit Compound Butter,15.07,45,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,False,False,False,3.0,1,635085,Black Bottom Banana Bars,78.85,45,5,...,2.63,13.13,0.32,21.09,100.80,10.08,0.28,1.53,9.89,3.30
3,True,False,True,2.0,1,663229,The Best Raw Chocolate Chip Cookies,54.64,45,12,...,0.65,3.26,0.10,6.47,26.79,2.68,NaN,NaN,NaN,NaN
4,False,True,False,31.0,3,651437,Mediterranean Spinach Artichoke Dip,115.26,45,8,...,0.66,3.29,0.07,4.64,162.84,16.28,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,False,True,True,18.0,13,638315,"Chicken Sausage, White Bean and Cabbage Soup",196.23,45,6,...,0.53,2.67,0.15,10.23,102.67,10.27,NaN,NaN,NaN,NaN
146,True,False,False,1.0,2,656248,Pinot Noir Brownies,65.76,45,16,...,0.21,1.07,0.03,1.68,19.82,1.98,2.48,13.76,10.69,3.56
147,True,True,True,93.0,2,637297,Cauliflower Chickpea Stew,139.28,45,4,...,4.77,23.83,0.45,29.70,141.16,14.12,NaN,NaN,NaN,NaN
148,True,True,False,5.0,1,659412,Saut√©ed Balsamic Green Beans With Cherry Tomatoes,101.81,45,4,...,1.15,5.73,0.12,7.85,55.64,5.56,NaN,NaN,NaN,NaN
149,True,True,True,100.0,4,647875,Indian-Style Dill and Turmeric Potato Salad,117.24,30,4,...,0.21,1.05,NaN,NaN,27.96,2.80,NaN,NaN,NaN,NaN

#### Some questions to think of for yourself. Feel free to ask us if you are in doubt, we are open for a discussion! :)

1. Are there any other columns in this dataset that you would consider a candidate for the index column? Why isn't is always a good idea to use a string as index?
2. Take a closer look at arguments "axis" and "inplace" in functions drop(...) and rename(...). Maybe google for documentation if you are not sure what they mean.
        What happens if you wanted to rename a column that is not there?
        What happens if you set the argument inplace=True?

1-. Mixing strings for indexing can be a little harder?
2-. If there are not columns in the data set then i will just use the rename function = data. rename( columns={0 :'new column name'}, inplace=True)

In [9]:
### good answers. Yes it will be harder to access items with a string index
### But the second question meant more ... if the column you were trying to rename doesn't exist ... what would happen then?
### Simply nothing will happen since it doesn't exist

#### Import pandas library using alias pd.

In [10]:
import pandas as pd

#### Load file recipes.csv from the data subfolder and store it in a variable df_ex1. Use the first column as index.

In [11]:
df_ex1 = pd.read_csv("data/recipes.csv",index_col=0)
df_ex1

,vegetarian,glutenFree,dairyFree,veryHealthy,healthScore,aggregateLikes,id,title,pricePerServing,readyInMinutes,...,VitaminB3Amount,VitaminB3percentOfDailyNeed,VitaminB1Amount,VitaminB1percentOfDailyNeed,CalciumAmount,CalciumpercentOfDailyNeed,AlcoholAmount,AlcoholpercentOfDailyNeed,CaffeineAmount,CaffeinepercentOfDailyNeed
0,True,True,True,False,1.0,3,633998,Banana Blueberry Pancakes,55.79,45,...,0.49,2.44,0.03,2.26,18.11,1.81,NaN,NaN,NaN,NaN
1,True,True,False,False,0.0,1,634426,Basil and Orange Confit Compound Butter,15.07,45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,False,False,False,False,3.0,1,635085,Black Bottom Banana Bars,78.85,45,...,2.63,13.13,0.32,21.09,100.80,10.08,0.28,1.53,9.89,3.30
3,True,False,True,False,2.0,1,663229,The Best Raw Chocolate Chip Cookies,54.64,45,...,0.65,3.26,0.10,6.47,26.79,2.68,NaN,NaN,NaN,NaN
4,False,True,False,False,31.0,3,651437,Mediterranean Spinach Artichoke Dip,115.26,45,...,0.66,3.29,0.07,4.64,162.84,16.28,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,False,True,True,False,18.0,13,638315,"Chicken Sausage, White Bean and Cabbage Soup",196.23,45,...,0.53,2.67,0.15,10.23,102.67,10.27,NaN,NaN,NaN,NaN
146,True,False,False,False,1.0,2,656248,Pinot Noir Brownies,65.76,45,...,0.21,1.07,0.03,1.68,19.82,1.98,2.48,13.76,10.69,3.56
147,True,True,True,True,93.0,2,637297,Cauliflower Chickpea Stew,139.28,45,...,4.77,23.83,0.45,29.70,141.16,14.12,NaN,NaN,NaN,NaN
148,True,True,False,False,5.0,1,659412,Saut√©ed Balsamic Green Beans With Cherry Tomatoes,101.81,45,...,1.15,5.73,0.12,7.85,55.64,5.56,NaN,NaN,NaN,NaN
149,True,True,True,True,100.0,4,647875,Indian-Style Dill and Turmeric Potato Salad,117.24,30,...,0.21,1.05,NaN,NaN,27.96,2.80,NaN,NaN,NaN,NaN

#### See if the 34th recipe on the list is vegetarian (remember the 0-based indexing!). Please do this in 4 different ways. Be careful with how .iloc and .loc handle things.

In [12]:
df_ex1['vegetarian'][33]

True

In [13]:
df_ex1.iloc[33,1]
##iloc selects rows and columns at specific integer positions##

True

In [14]:
df_ex1.loc[33, 'vegetarian']
##loc selects rows and columns with specific labels##

True

#### Choose columns with the following info and in the following order: title, price and if it is vegetarian

In [15]:
df_ex1.loc[:,['title','pricePerServing','vegetarian']]

,title,pricePerServing,vegetarian
0,Banana Blueberry Pancakes,55.79,True
1,Basil and Orange Confit Compound Butter,15.07,True
2,Black Bottom Banana Bars,78.85,False
3,The Best Raw Chocolate Chip Cookies,54.64,True
4,Mediterranean Spinach Artichoke Dip,115.26,False
...,...,...,...
145,"Chicken Sausage, White Bean and Cabbage Soup",196.23,False
146,Pinot Noir Brownies,65.76,True
147,Cauliflower Chickpea Stew,139.28,True
148,Saut√©ed Balsamic Green Beans With Cherry Tomatoes,101.81,True
149,Indian-Style Dill and Turmeric Potato Salad,117.24,True

#### And now the same for recipes number from 24 to 29

In [16]:
df_ex1.loc[24:29]

,vegetarian,glutenFree,dairyFree,veryHealthy,healthScore,aggregateLikes,id,title,pricePerServing,readyInMinutes,...,VitaminB3Amount,VitaminB3percentOfDailyNeed,VitaminB1Amount,VitaminB1percentOfDailyNeed,CalciumAmount,CalciumpercentOfDailyNeed,AlcoholAmount,AlcoholpercentOfDailyNeed,CaffeineAmount,CaffeinepercentOfDailyNeed
24,True,True,False,False,6.0,7,645416,Green Beans with Garlic Chips,83.90,45,...,1.28,6.42,0.15,10.04,73.38,7.34,NaN,NaN,NaN,NaN
25,False,False,False,False,0.0,1,654516,Pandan Thumbprint Biscuits,54.26,45,...,0.57,2.87,0.06,3.83,NaN,NaN,NaN,NaN,18.48,6.16
26,False,False,False,False,42.0,1,649225,Lamb Moussaka,528.50,45,...,30.58,152.90,0.46,30.62,478.31,47.83,1.05,5.83,NaN,NaN
27,True,True,False,False,19.0,2,641962,Easy Eggplant Parmesan,195.51,45,...,2.02,10.12,0.10,6.86,156.77,15.68,NaN,NaN,NaN,NaN
28,True,False,False,False,3.0,7,655145,Peach Pie,173.52,45,...,1.68,8.41,0.16,10.93,116.78,11.68,0.75,4.14,NaN,NaN
29,True,True,True,False,19.0,1,648742,Kappa Maki,72.94,45,...,2.03,10.15,0.19,12.73,21.56,2.16,NaN,NaN,NaN,NaN

#### Play with some slicing and accesing. Do you understand the result that you obtain from different trials? Please feel free to ask us about what you see! :)

In [17]:
df_ex1.iloc[ -30: , : ]

,vegetarian,glutenFree,dairyFree,veryHealthy,healthScore,aggregateLikes,id,title,pricePerServing,readyInMinutes,...,VitaminB3Amount,VitaminB3percentOfDailyNeed,VitaminB1Amount,VitaminB1percentOfDailyNeed,CalciumAmount,CalciumpercentOfDailyNeed,AlcoholAmount,AlcoholpercentOfDailyNeed,CaffeineAmount,CaffeinepercentOfDailyNeed
120,True,False,False,False,16.0,1,662558,Sweet Potato Bars,39.68,45,...,0.36,1.79,0.11,7.09,57.54,5.75,NaN,NaN,NaN,NaN
121,False,False,False,False,16.0,1,639584,Classic Clam Sauce,225.65,45,...,0.84,4.21,0.06,3.87,70.35,7.03,6.18,34.33,NaN,NaN
122,True,False,False,False,3.0,0,673449,How to Make a Skillet Cornbread,44.66,35,...,1.66,8.32,0.23,15.53,149.40,14.94,NaN,NaN,NaN,NaN
123,True,True,True,True,100.0,1,659689,Seasonal Autumn Stew,172.76,45,...,6.15,30.77,0.38,25.44,213.53,21.35,NaN,NaN,NaN,NaN
124,False,False,False,False,0.0,19,665193,White Chocolate Raspberry Brie Cups,37.09,20,...,NaN,NaN,NaN,NaN,12.49,1.25,NaN,NaN,NaN,NaN
125,False,False,False,False,1.0,11,665573,Yorkshire Pudding,12.65,45,...,1.31,6.56,0.09,6.12,58.26,5.83,NaN,NaN,NaN,NaN
126,True,True,True,False,21.0,1,1096231,Slow Cooker Healthy Sweet Potato Soup with Coc...,418.08,275,...,2.00,9.99,0.26,17.24,104.01,10.40,NaN,NaN,NaN,NaN
127,False,True,True,True,66.0,1,643945,"Fruit and Spinach Salad with ""Xocai Activ"" Vin...",97.39,45,...,0.48,2.41,0.06,4.20,52.83,5.28,NaN,NaN,NaN,NaN
128,True,False,False,False,8.0,1,647693,Ice Cream Biscuits,179.24,45,...,1.07,5.35,0.27,18.26,64.32,6.43,NaN,NaN,NaN,NaN
129,True,True,True,False,14.0,1,1096178,"Blueberry, Persimmon Smoothie with Banana and ...",48.70,5,...,2.97,14.85,0.06,3.78,59.51,5.95,NaN,NaN,NaN,NaN
130,False,True,True,False,4.0,2,647615,Huli-Huli Chicken,62.54,45,...,8.10,40.50,0.10,6.96,23.44,2.34,NaN,NaN,NaN,NaN
131,True,True,False,False,7.0,1,650772,Mango Cranberry Sherbet,144.10,45,...,0.85,4.24,0.10,6.53,163.17,16.32,NaN,NaN,NaN,NaN
132,True,True,False,False,16.0,1,637705,Cherries and Yogurt Parfait,277.28,45,...,0.63,3.15,0.19,12.82,472.85,47.29,1.03,5.73,NaN,NaN
133,True,True,True,False,7.0,6,663313,The Pearhattan Cocktail,509.89,45,...,1.09,5.44,0.10,6.92,63.01,6.30,21.31,118.40,NaN,NaN
134,True,True,True,True,77.0,1,1096268,Garlic-Roasted Brussels Sprouts Side Dish,170.34,35,...,1.23,6.13,0.23,15.57,83.41,8.34,NaN,NaN,NaN,NaN
135,False,True,True,False,13.0,1,639843,Cod Fillet In Lemon Grass Shallot Sauce,307.35,45,...,0.51,2.54,0.10,6.91,72.79,7.28,NaN,NaN,NaN,NaN
136,False,False,False,False,2.0,1,655189,Peaches and Cream Pound Cake,89.63,45,...,0.86,4.30,0.05,3.37,75.85,7.59,NaN,NaN,NaN,NaN
137,False,True,True,True,67.0,19,639411,Cilantro Lime Halibut,874.74,45,...,15.43,77.15,0.14,9.49,35.74,3.57,3.09,17.17,NaN,NaN
138,True,False,True,False,12.0,1,662315,"Sundried Tomato,Olive,Rosemary and Thyme Focca...",81.78,45,...,2.00,9.99,0.46,30.84,NaN,NaN,NaN,NaN,NaN,NaN
139,True,True,False,False,37.0,1,649354,Layered Greek Salad,123.12,45,...,0.76,3.79,0.14,9.32,286.72,28.67,NaN,NaN,NaN,NaN
140,True,False,False,False,25.0,11,636178,"Broccoli Cheddar Soup, A Panera Bread Co. Copycat",196.38,45,...,4.04,20.18,0.23,15.23,605.26,60.53,NaN,NaN,NaN,NaN
141,False,True,False,True,55.0,3,644173,Garbanzo Beans & Greens,339.93,45,...,6.82,34.11,0.39,25.73,248.54,24.85,NaN,NaN,NaN,NaN
142,False,True,True,False,10.0,1,659290,Satay Chicken Wings,154.81,45,...,9.00,45.02,0.12,8.09,66.44,6.64,NaN,NaN,NaN,NaN
143,True,True,True,False,50.0,6,661653,Stir Fried Cabbage and Tomatoes,80.89,45,...,1.40,7.02,0.19,12.73,110.71,11.07,NaN,NaN,NaN,NaN
144,True,False,False,False,0.0,11,647442,Hot Cross Buns,11.23,45,...,NaN,NaN,0.02,1.64,34.67,3.47,NaN,NaN,NaN,NaN
145,False,True,True,False,18.0,13,638315,"Chicken Sausage, White Bean and Cabbage Soup",196.23,45,...,0.53,2.67,0.15,10.23,102.67,10.27,NaN,NaN,NaN,NaN
146,True,False,False,False,1.0,2,656248,Pinot Noir Brownies,65.76,45,...,0.21,1.07,0.03,1.68,19.82,1.98,2.48,13.76,10.69,3.56
147,True,True,True,True,93.0,2,637297,Cauliflower Chickpea Stew,139.28,45,...,4.77,23.83,0.45,29.70,141.16,14.12,NaN,NaN,NaN,NaN
148,True,True,False,False,5.0,1,659412,Saut√©ed Balsamic Green Beans With Cherry Tomatoes,101.81,45,...,1.15,5.73,0.12,7.85,55.64,5.56,NaN,NaN,NaN,NaN
149,True,True,True,True,100.0,4,647875,Indian-Style Dill and Turmeric Potato Salad,117.24,30,...,0.21,1.05,NaN,NaN,27.96,2.80,NaN,NaN,NaN,NaN

#### Notice which slicing methods are inclusive and which of them are exclusive. Try to figure your favourite way of accesing / slicing and remember that sometimes some of them make more sense than the others.

### Class-exercise 2

In [19]:
import numpy as np

1. Create a 2-d and 3-d numpy integer array

In [20]:
np_2d = np.array([[1,2,3],[4,5,6]])
np_3d = np.array([[1,2,3],[4,5,6],[7,8,9]])

2. Create a 2X2 integer array and show it's dimensions

In [21]:
np_2x2 = np.array([[1,2],[3,4]])
np_2x2.ndim

2

3. Create a numpy array and  print the sum of third and fourth elements from the array

In [22]:
array = np.array([150,300,500,800,960])
print(array[2]+array[3])

1300

4. Slice the below array to get the the second item to the excluding fifth item

arr = np.array([10, 15, 20, 25, 30, 35, 40])

In [24]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])
print(arr[1], arr[3])

### that wasn't slicing, you just got two items :) You need to get everything in between 2nd and 5th

15 25

5. Try example 4. using STEP method

In [25]:
print(arr[1:5:2])

[15 25]

6. Create a integer array and change data type from integer to boolean

In [26]:
np.array([0,1,0,1,2,3],dtype=bool)

array([False,  True, False,  True,  True,  True])

In [27]:
array_int = np.array([0,1,0,1,2,3])
array_bool = array_int.astype(bool)
array_bool

array([False,  True, False,  True,  True,  True])

7. Use NumPy syntax to check the shape of an array.

arr = np.array([1, 2, 3, 4, 5])

In [28]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.shape)

(5,)

8. Find the indexes where the values are even:

arr = [16, 8, 3, 7, 15, 24]

In [29]:
arr = np.array([16, 8, 3, 7, 15, 24])
x = np.where(arr % 2 == 0)

print(x)

(array([0, 1, 5]),)

9. Create a numpy array of 5 person names and sort the values alpbabetically

In [30]:
np_array = np.array(['Claudia','Stefanie','Daniel','Jorge','Sofia'])
print(np.sort(np_array))

['Claudia' 'Daniel' 'Jorge' 'Sofia' 'Stefanie']

10. Use the correct NumPy method to return a sorted array.

  arr = np.array([3, 2, 0, 1])

In [31]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]

In [32]:
### Great job! That was all well done :)