#### Hi! Today you will play with NaN values and another Data Manipulation methods. Let us know if you need help and also if you need more challenges on that :)

#### The dataset that you will use is again recipes.csv. You can either use your own or the one in the subfolder "data". Do not forget to import the necessary libraries!

In [12]:
import pandas as pd
import numpy as np


df = pd.read_csv("data/recipes.csv", index_col=0)
df.head()

,vegetarian,glutenFree,dairyFree,veryHealthy,healthScore,aggregateLikes,id,title,pricePerServing,readyInMinutes,...,VitaminB3Amount,VitaminB3percentOfDailyNeed,VitaminB1Amount,VitaminB1percentOfDailyNeed,CalciumAmount,CalciumpercentOfDailyNeed,AlcoholAmount,AlcoholpercentOfDailyNeed,CaffeineAmount,CaffeinepercentOfDailyNeed
0,True,True,True,False,1.0,3,633998,Banana Blueberry Pancakes,55.79,45,...,0.49,2.44,0.03,2.26,18.11,1.81,NaN,NaN,NaN,NaN
1,True,True,False,False,0.0,1,634426,Basil and Orange Confit Compound Butter,15.07,45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,False,False,False,False,3.0,1,635085,Black Bottom Banana Bars,78.85,45,...,2.63,13.13,0.32,21.09,100.80,10.08,0.28,1.53,9.89,3.3
3,True,False,True,False,2.0,1,663229,The Best Raw Chocolate Chip Cookies,54.64,45,...,0.65,3.26,0.10,6.47,26.79,2.68,NaN,NaN,NaN,NaN
4,False,True,False,False,31.0,3,651437,Mediterranean Spinach Artichoke Dip,115.26,45,...,0.66,3.29,0.07,4.64,162.84,16.28,NaN,NaN,NaN,NaN

#### Print the names of Columns that have null values

In [13]:
df.columns[df.isnull().any()].tolist()

['FiberAmount',
 'FiberpercentOfDailyNeed',
 'VitaminB6Amount',
 'VitaminB6percentOfDailyNeed',
 'ManganeseAmount',
 'ManganesepercentOfDailyNeed',
 'SeleniumAmount',
 'SeleniumpercentOfDailyNeed',
 'PotassiumAmount',
 'PotassiumpercentOfDailyNeed',
 'VitaminB2Amount',
 'VitaminB2percentOfDailyNeed',
 'VitaminCAmount',
 'VitaminCpercentOfDailyNeed',
 'PhosphorusAmount',
 'PhosphoruspercentOfDailyNeed',
 'FolateAmount',
 'FolatepercentOfDailyNeed',
 'VitaminB5Amount',
 'VitaminB5percentOfDailyNeed',
 'MagnesiumAmount',
 'MagnesiumpercentOfDailyNeed',
 'IronAmount',
 'IronpercentOfDailyNeed',
 'VitaminKAmount',
 'VitaminKpercentOfDailyNeed',
 'CopperAmount',
 'CopperpercentOfDailyNeed',
 'VitaminAAmount',
 'VitaminApercentOfDailyNeed',
 'VitaminB12Amount',
 'VitaminB12percentOfDailyNeed',
 'VitaminDAmount',
 'VitaminDpercentOfDailyNeed',
 'ZincAmount',
 'ZincpercentOfDailyNeed',
 'VitaminEAmount',
 'VitaminEpercentOfDailyNeed',
 'VitaminB3Amount',
 'VitaminB3percentOfDailyNeed',
 'VitaminB1Amount',
 'VitaminB1percentOfDailyNeed',
 'CalciumAmount',
 'CalciumpercentOfDailyNeed',
 'AlcoholAmount',
 'AlcoholpercentOfDailyNeed',
 'CaffeineAmount',
 'CaffeinepercentOfDailyNeed']

#### Print the recipes with the highest number of aggregateLikes

In [14]:
column = df["aggregateLikes"]
max_value = column.max()
print(max_value)

16911

In [15]:
i = df['aggregateLikes'].idxmax()
print(i)
# display the name corresponding this index
print(df['title'][i])

50
Slow Cooker Spicy Hot Wings

#### Handle the missing values of “calcium percent of Daily need”. Sort the resulting DataFrame by id column.

In [16]:
df['CalciumpercentOfDailyNeed'].isnull().sum() #check how many null values in dataset

8

In [17]:
df['CalciumpercentOfDailyNeed'] = df['CalciumpercentOfDailyNeed'].fillna(0)
#https://pythonsansar.com/how-to-handle-null-values-in-pandas/

In [18]:
df['CalciumpercentOfDailyNeed'].isnull().sum()

0

In [19]:
df.sort_values(by='id',inplace=True)
df

,vegetarian,glutenFree,dairyFree,veryHealthy,healthScore,aggregateLikes,id,title,pricePerServing,readyInMinutes,...,VitaminB3Amount,VitaminB3percentOfDailyNeed,VitaminB1Amount,VitaminB1percentOfDailyNeed,CalciumAmount,CalciumpercentOfDailyNeed,AlcoholAmount,AlcoholpercentOfDailyNeed,CaffeineAmount,CaffeinepercentOfDailyNeed
83,False,False,False,False,5.0,0,45945,Oeufs En Meurette,209.85,328,...,1.51,7.56,0.15,10.13,124.54,12.45,NaN,NaN,NaN,NaN
43,False,False,False,False,44.0,1,622825,Tortilla Burger Loco Vaca,407.86,40,...,12.82,64.12,0.35,23.42,281.97,28.20,NaN,NaN,NaN,NaN
104,False,False,False,False,4.0,1,631769,"Bad Boy"" Giant Double Chocolate Cookies",44.08,45,...,1.73,8.63,0.20,13.42,64.05,6.41,NaN,NaN,34.04,11.35
95,False,True,True,False,9.0,1,632084,Allergy-Free Stuffed Portobello Mushrooms,138.47,45,...,4.59,22.96,0.09,6.05,28.08,2.81,NaN,NaN,NaN,NaN
52,False,False,False,False,2.0,16,632101,Almond Butter and Chocolate Squares,92.26,45,...,0.81,4.04,0.04,2.51,86.99,8.70,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,True,True,True,True,77.0,1,1096268,Garlic-Roasted Brussels Sprouts Side Dish,170.34,35,...,1.23,6.13,0.23,15.57,83.41,8.34,NaN,NaN,NaN,NaN
30,True,True,True,False,17.0,1,1096306,Vegan Chana Masala Curry,165.89,30,...,2.14,10.71,0.20,13.09,154.27,15.43,NaN,NaN,NaN,NaN
118,False,True,True,False,38.0,1,1096323,Potato & Leek Soup with Roasted Beets,244.08,45,...,2.43,12.15,0.10,6.47,101.41,10.14,NaN,NaN,NaN,NaN
39,True,True,True,False,7.0,6,1098357,Three Ingredient Frozen Pina Colada,214.60,5,...,1.05,5.25,0.19,12.66,52.87,5.29,13.36,74.22,NaN,NaN
67,False,True,False,False,15.0,0,1416203,Tater Tot Chili Cheese Casserole,81.27,40,...,1.24,6.19,0.08,5.16,148.34,14.83,NaN,NaN,NaN,NaN

#### Delete the columns that have null values == 141

In [20]:
df.isnull().sum() #sum returns the number of null values in the dataset
#141 null values in the dataset

vegetarian                      0
glutenFree                      0
dairyFree                       0
veryHealthy                     0
healthScore                     0
                             ...
CalciumpercentOfDailyNeed       0
AlcoholAmount                 129
AlcoholpercentOfDailyNeed     129
CaffeineAmount                141
CaffeinepercentOfDailyNeed    141
Length: 78, dtype: int64

In [21]:
colname = df[df.columns[df.isnull().sum()==141]]
colname

     CaffeineAmount  CaffeinepercentOfDailyNeed
83              NaN                         NaN
43              NaN                         NaN
104           34.04                       11.35
95              NaN                         NaN
52              NaN                         NaN
..              ...                         ...
134             NaN                         NaN
30              NaN                         NaN
118             NaN                         NaN
39              NaN                         NaN
67              NaN                         NaN

[150 rows x 2 columns]

In [22]:
df=df.drop(columns=colname)
df.isnull().sum()

vegetarian                       0
glutenFree                       0
dairyFree                        0
veryHealthy                      0
healthScore                      0
                              ...
VitaminB1percentOfDailyNeed      7
CalciumAmount                    8
CalciumpercentOfDailyNeed        0
AlcoholAmount                  129
AlcoholpercentOfDailyNeed      129
Length: 76, dtype: int64

#### Print the title of the recipes that are vegetarian == TRUE and glutenFree == True

In [23]:
new_df = df.loc[(df.vegetarian == True ) & (df.glutenFree == True )]
new_df['title']

0                              Banana Blueberry Pancakes
1                Basil and Orange Confit Compound Butter
85                                             Beet Slaw
100                                  Blender Carrot Soup
107                           Blueberry Mojito Popsicles
96                                    Breakfast Porridge
22                                 Butternut Squash Soup
147                            Cauliflower Chickpea Stew
132                          Cherries and Yogurt Parfait
101                                      Dandelion pesto
33                             Detox Orange Carrot Juice
27                                Easy Eggplant Parmesan
72                             EASY, CUMIN-LENTIL SPREAD
20                           Fire Roasted Tomato Chutney
119                                     Fried Brown Rice
24                         Green Beans with Garlic Chips
149          Indian-Style Dill and Turmeric Potato Salad
106                              Japanese Cucumber Salad
29                                            Kappa Maki
139                                  Layered Greek Salad
80                                 Luscious Palak Paneer
131                              Mango Cranberry Sherbet
15                                            Nutty Rice
42                               Peach Coconut Ice Cream
97     Peanut Butter Cookies with Flax Seeds and Choc...
37                      Roasted Asparagus with Egg Salad
93             Roasted Strawberry Coconut Milk Ice Cream
148    Sautéed Balsamic Green Beans With Cherry Tomatoes
57     Sautéed Balsamic Green Beans With Cherry Tomatoes
123                                 Seasonal Autumn Stew
14                            Spicy Carrot Amaranth Soup
143                      Stir Fried Cabbage and Tomatoes
133                              The Pearhattan Cocktail
69                      Chicken with Avocado Peach Salsa
31     Grilled Peach Melba with Vanilla Bean Frozen Y...
61                              Ginger Melon Side Salad
102                                Coconut Flour Muffins
129    Blueberry, Persimmon Smoothie with Banana and ...
126    Slow Cooker Healthy Sweet Potato Soup with Coc...
134            Garlic-Roasted Brussels Sprouts Side Dish
30                              Vegan Chana Masala Curry
39                   Three Ingredient Frozen Pina Colada
Name: title, dtype: object

#### How many vegan recipes are there (Vegan = Vegetarian and dairy free)?

In [24]:
vegandf = df.loc[(df.vegetarian == True ) & (df.dairyFree == True )]
#vegandf
len(vegandf.index)

29

#### Compare the average amount of Vitamin B12 for the vegan and non-vegan recipes. How reliable are the results?

In [25]:
nonvegandf = df.loc[(df.vegetarian == False )]
nonvegandf
averagevegan = vegandf["VitaminB12Amount"].mean()
averagenonvegan = nonvegandf["VitaminB12Amount"].mean()
averagevegan,averagenonvegan

(0.24333333333333332, 1.2353846153846157)

#### Compare the average health Score for both types of recipes (vegan vs non-vegan).

In [26]:
avgHSNV = nonvegandf["healthScore"].mean()
avgHSVEG = vegandf["healthScore"].mean()
avgHSNV,avgHSVEG

(22.107142857142858, 27.724137931034484)

#### Create a new column: "VeganWeek" where you decrease the price of vegan products by 10%, but only if they already cost more than 100.

In [27]:
#df.loc[(df.vegetarian == True ) & (df.dairyFree == True) & ( df.pricePerServing > 100 )]
df.loc[(df.vegetarian == True ) & (df.dairyFree == True) & ( df.pricePerServing > 100 ),"pricePerServing"]= df.pricePerServing * .9
#df
df["VeganWeek"] = np.where((df.vegetarian == True ) & (df.dairyFree == True ),  "VeganWeek " + df.title, "NOT Vegan " + df.title)
#df.loc[(df.vegetarian == True ) & (df.dairyFree == True) & ( df.pricePerServing > 100 )]
df

,vegetarian,glutenFree,dairyFree,veryHealthy,healthScore,aggregateLikes,id,title,pricePerServing,readyInMinutes,...,VitaminEpercentOfDailyNeed,VitaminB3Amount,VitaminB3percentOfDailyNeed,VitaminB1Amount,VitaminB1percentOfDailyNeed,CalciumAmount,CalciumpercentOfDailyNeed,AlcoholAmount,AlcoholpercentOfDailyNeed,VeganWeek
83,False,False,False,False,5.0,0,45945,Oeufs En Meurette,209.850,328,...,5.61,1.51,7.56,0.15,10.13,124.54,12.45,NaN,NaN,NOT Vegan Oeufs En Meurette
43,False,False,False,False,44.0,1,622825,Tortilla Burger Loco Vaca,407.860,40,...,30.71,12.82,64.12,0.35,23.42,281.97,28.20,NaN,NaN,NOT Vegan Tortilla Burger Loco Vaca
104,False,False,False,False,4.0,1,631769,"Bad Boy"" Giant Double Chocolate Cookies",44.080,45,...,3.52,1.73,8.63,0.20,13.42,64.05,6.41,NaN,NaN,"NOT Vegan Bad Boy"" Giant Double Chocolate Cookies"
95,False,True,True,False,9.0,1,632084,Allergy-Free Stuffed Portobello Mushrooms,138.470,45,...,7.19,4.59,22.96,0.09,6.05,28.08,2.81,NaN,NaN,NOT Vegan Allergy-Free Stuffed Portobello Mush...
52,False,False,False,False,2.0,16,632101,Almond Butter and Chocolate Squares,92.260,45,...,26.52,0.81,4.04,0.04,2.51,86.99,8.70,NaN,NaN,NOT Vegan Almond Butter and Chocolate Squares
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,True,True,True,True,77.0,1,1096268,Garlic-Roasted Brussels Sprouts Side Dish,153.306,35,...,29.33,1.23,6.13,0.23,15.57,83.41,8.34,NaN,NaN,VeganWeek Garlic-Roasted Brussels Sprouts Side...
30,True,True,True,False,17.0,1,1096306,Vegan Chana Masala Curry,149.301,30,...,22.26,2.14,10.71,0.20,13.09,154.27,15.43,NaN,NaN,VeganWeek Vegan Chana Masala Curry
118,False,True,True,False,38.0,1,1096323,Potato & Leek Soup with Roasted Beets,244.080,45,...,8.76,2.43,12.15,0.10,6.47,101.41,10.14,NaN,NaN,NOT Vegan Potato & Leek Soup with Roasted Beets
39,True,True,True,False,7.0,6,1098357,Three Ingredient Frozen Pina Colada,193.140,5,...,NaN,1.05,5.25,0.19,12.66,52.87,5.29,13.36,74.22,VeganWeek Three Ingredient Frozen Pina Colada
67,False,True,False,False,15.0,0,1416203,Tater Tot Chili Cheese Casserole,81.270,40,...,3.35,1.24,6.19,0.08,5.16,148.34,14.83,NaN,NaN,NOT Vegan Tater Tot Chili Cheese Casserole

#### Among the non-vegan recipes, find the one requiring most time to prepare. How is it called?

In [28]:
Msttimeprepare = nonvegandf['readyInMinutes'].idxmax()
print(Msttimeprepare)
# display the name corresponding this index
print(df['title'][Msttimeprepare])

83
Oeufs En Meurette