#### Hi! Today you will play with NaN values and another Data Manipulation methods. Let us know if you need help and also if you need more challenges on that :)

#### The dataset that you will use is again recipes.csv. You can either use your own or the one in the subfolder "data". Do not forget to import the necessary libraries!

In [2]:
import pandas as pd
import numpy as np

df_receipe = pd.read_csv('data/Recipes.csv',index_col=0)
df_receipe.head()

,vegetarian,glutenFree,dairyFree,veryHealthy,healthScore,aggregateLikes,id,title,pricePerServing,readyInMinutes,...,VitaminB3Amount,VitaminB3percentOfDailyNeed,VitaminB1Amount,VitaminB1percentOfDailyNeed,CalciumAmount,CalciumpercentOfDailyNeed,AlcoholAmount,AlcoholpercentOfDailyNeed,CaffeineAmount,CaffeinepercentOfDailyNeed
0,True,True,True,False,1.0,3,633998,Banana Blueberry Pancakes,55.79,45,...,0.49,2.44,0.03,2.26,18.11,1.81,NaN,NaN,NaN,NaN
1,True,True,False,False,0.0,1,634426,Basil and Orange Confit Compound Butter,15.07,45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,False,False,False,False,3.0,1,635085,Black Bottom Banana Bars,78.85,45,...,2.63,13.13,0.32,21.09,100.80,10.08,0.28,1.53,9.89,3.3
3,True,False,True,False,2.0,1,663229,The Best Raw Chocolate Chip Cookies,54.64,45,...,0.65,3.26,0.10,6.47,26.79,2.68,NaN,NaN,NaN,NaN
4,False,True,False,False,31.0,3,651437,Mediterranean Spinach Artichoke Dip,115.26,45,...,0.66,3.29,0.07,4.64,162.84,16.28,NaN,NaN,NaN,NaN

In [3]:
df_receipe.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 150 entries, 0 to 149
Data columns (total 78 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   vegetarian                          150 non-null    bool
 1   glutenFree                          150 non-null    bool
 2   dairyFree                           150 non-null    bool
 3   veryHealthy                         150 non-null    bool
 4   healthScore                         150 non-null    float64
 5   aggregateLikes                      150 non-null    int64
 6   id                                  150 non-null    int64
 7   title                               150 non-null    object
 8   pricePerServing                     150 non-null    float64
 9   readyInMinutes                      150 non-null    int64
 10  servings                            150 non-null    int64
 11  sourceUrl                           150 non-null    object
 12  CaloriesAmount                      150 non-null    float64
 13  CaloriespercentOfDailyNeed          150 non-null    float64
 14  FatAmount                           150 non-null    float64
 15  FatpercentOfDailyNeed               150 non-null    float64
 16  SaturatedFatAmount                  150 non-null    float64
 17  SaturatedFatpercentOfDailyNeed      150 non-null    float64
 18  CarbohydratesAmount                 150 non-null    float64
 19  CarbohydratespercentOfDailyNeed     150 non-null    float64
 20  NetCarbohydratesAmount              150 non-null    float64
 21  NetCarbohydratespercentOfDailyNeed  150 non-null    float64
 22  SugarAmount                         150 non-null    float64
 23  SugarpercentOfDailyNeed             150 non-null    float64
 24  CholesterolAmount                   150 non-null    float64
 25  CholesterolpercentOfDailyNeed       150 non-null    float64
 26  SodiumAmount                        150 non-null    float64
 27  SodiumpercentOfDailyNeed            150 non-null    float64
 28  ProteinAmount                       150 non-null    float64
 29  ProteinpercentOfDailyNeed           150 non-null    float64
 30  FiberAmount                         142 non-null    float64
 31  FiberpercentOfDailyNeed             142 non-null    float64
 32  VitaminB6Amount                     140 non-null    float64
 33  VitaminB6percentOfDailyNeed         140 non-null    float64
 34  ManganeseAmount                     146 non-null    float64
 35  ManganesepercentOfDailyNeed         146 non-null    float64
 36  SeleniumAmount                      134 non-null    float64
 37  SeleniumpercentOfDailyNeed          134 non-null    float64
 38  PotassiumAmount                     143 non-null    float64
 39  PotassiumpercentOfDailyNeed         143 non-null    float64
 40  VitaminB2Amount                     146 non-null    float64
 41  VitaminB2percentOfDailyNeed         146 non-null    float64
 42  VitaminCAmount                      119 non-null    float64
 43  VitaminCpercentOfDailyNeed          119 non-null    float64
 44  PhosphorusAmount                    147 non-null    float64
 45  PhosphoruspercentOfDailyNeed        147 non-null    float64
 46  FolateAmount                        144 non-null    float64
 47  FolatepercentOfDailyNeed            144 non-null    float64
 48  VitaminB5Amount                     136 non-null    float64
 49  VitaminB5percentOfDailyNeed         136 non-null    float64
 50  MagnesiumAmount                     142 non-null    float64
 51  MagnesiumpercentOfDailyNeed         142 non-null    float64
 52  IronAmount                          147 non-null    float64
 53  IronpercentOfDailyNeed              147 non-null    float64
 54  VitaminKAmount                      138 non-null    float64
 55  VitaminKpercentOfDailyNeed          138 non-null    float64
 56  CopperAmount                        144 non-null    float64
 57  CopperpercentOfDailyNeed            144 non-null    float64
 58  VitaminAAmount                      137 non-null    float64
 59  VitaminApercentOfDailyNeed          137 non-null    float64
 60  VitaminB12Amount                    93 non-null     float64
 61  VitaminB12percentOfDailyNeed        93 non-null     float64
 62  VitaminDAmount                      75 non-null     float64
 63  VitaminDpercentOfDailyNeed          75 non-null     float64
 64  ZincAmount                          139 non-null    float64
 65  ZincpercentOfDailyNeed              139 non-null    float64
 66  VitaminEAmount                      138 non-null    float64
 67  VitaminEpercentOfDailyNeed          138 non-null    float64
 68  VitaminB3Amount                     139 non-null    float64
 69  VitaminB3percentOfDailyNeed         139 non-null    float64
 70  VitaminB1Amount                     143 non-null    float64
 71  VitaminB1percentOfDailyNeed         143 non-null    float64
 72  CalciumAmount                       142 non-null    float64
 73  CalciumpercentOfDailyNeed           142 non-null    float64
 74  AlcoholAmount                       21 non-null     float64
 75  AlcoholpercentOfDailyNeed           21 non-null     float64
 76  CaffeineAmount                      9 non-null      float64
 77  CaffeinepercentOfDailyNeed          9 non-null      float64
dtypes: bool(4), float64(68), int64(4), object(2)
memory usage: 88.5+ KB

#### Print the names of Columns that have null values

In [4]:
df_receipe.isnull().sum()

vegetarian                      0
glutenFree                      0
dairyFree                       0
veryHealthy                     0
healthScore                     0
                             ...
CalciumpercentOfDailyNeed       8
AlcoholAmount                 129
AlcoholpercentOfDailyNeed     129
CaffeineAmount                141
CaffeinepercentOfDailyNeed    141
Length: 78, dtype: int64

#### Print the recipes with the highest number of aggregateLikes

In [5]:
highestNum = df_receipe.groupby('title')['aggregateLikes'].max().sort_values(ascending=False)
highestNum.head(5)

title
Slow Cooker Spicy Hot Wings                                     16911
Chocolate nut spread                                              392
Grilled Peach Melba with Vanilla Bean Frozen Yogurt               249
Chicken Avocado Burger (Whole 30, PALEO, & Simple Fit Forty)      181
Blueberry Almond Crescent Rolls                                   122
Name: aggregateLikes, dtype: int64

#### Handle the missing values of “calcium percent of Daily need”. Sort the resulting DataFrame by id column.

In [6]:
df_receipe['CalciumpercentOfDailyNeed'].isnull().sum()

8

In [7]:
df_receipe['CalciumpercentOfDailyNeed'].fillna(float(df_receipe['CalciumpercentOfDailyNeed'].mean()), inplace=True)

In [8]:
df_receipe['CalciumpercentOfDailyNeed'].isnull().sum()

0

In [9]:
df_receipe.sort_values(by='id',inplace=True)
df_receipe.head()

,vegetarian,glutenFree,dairyFree,veryHealthy,healthScore,aggregateLikes,id,title,pricePerServing,readyInMinutes,...,VitaminB3Amount,VitaminB3percentOfDailyNeed,VitaminB1Amount,VitaminB1percentOfDailyNeed,CalciumAmount,CalciumpercentOfDailyNeed,AlcoholAmount,AlcoholpercentOfDailyNeed,CaffeineAmount,CaffeinepercentOfDailyNeed
83,False,False,False,False,5.0,0,45945,Oeufs En Meurette,209.85,328,...,1.51,7.56,0.15,10.13,124.54,12.45,NaN,NaN,NaN,NaN
43,False,False,False,False,44.0,1,622825,Tortilla Burger Loco Vaca,407.86,40,...,12.82,64.12,0.35,23.42,281.97,28.20,NaN,NaN,NaN,NaN
104,False,False,False,False,4.0,1,631769,"Bad Boy"" Giant Double Chocolate Cookies",44.08,45,...,1.73,8.63,0.20,13.42,64.05,6.41,NaN,NaN,34.04,11.35
95,False,True,True,False,9.0,1,632084,Allergy-Free Stuffed Portobello Mushrooms,138.47,45,...,4.59,22.96,0.09,6.05,28.08,2.81,NaN,NaN,NaN,NaN
52,False,False,False,False,2.0,16,632101,Almond Butter and Chocolate Squares,92.26,45,...,0.81,4.04,0.04,2.51,86.99,8.70,NaN,NaN,NaN,NaN

#### Delete the columns that have null values == 141

In [10]:
col = df_receipe[df_receipe.columns[df_receipe.isnull().sum()==141]]
col

     CaffeineAmount  CaffeinepercentOfDailyNeed
83              NaN                         NaN
43              NaN                         NaN
104           34.04                       11.35
95              NaN                         NaN
52              NaN                         NaN
..              ...                         ...
134             NaN                         NaN
30              NaN                         NaN
118             NaN                         NaN
39              NaN                         NaN
67              NaN                         NaN

[150 rows x 2 columns]

In [11]:
df_receipe1=df_receipe.drop(columns=col)
df_receipe1.isnull().sum()

vegetarian                       0
glutenFree                       0
dairyFree                        0
veryHealthy                      0
healthScore                      0
                              ...
VitaminB1percentOfDailyNeed      7
CalciumAmount                    8
CalciumpercentOfDailyNeed        0
AlcoholAmount                  129
AlcoholpercentOfDailyNeed      129
Length: 76, dtype: int64

#### Print the title of the recipes that are vegetarian == TRUE and glutenFree == True

In [12]:
mask1 = df_receipe1['vegetarian']
mask2 = df_receipe1['glutenFree']

df_receipe1[mask1&mask2]

,vegetarian,glutenFree,dairyFree,veryHealthy,healthScore,aggregateLikes,id,title,pricePerServing,readyInMinutes,...,VitaminEAmount,VitaminEpercentOfDailyNeed,VitaminB3Amount,VitaminB3percentOfDailyNeed,VitaminB1Amount,VitaminB1percentOfDailyNeed,CalciumAmount,CalciumpercentOfDailyNeed,AlcoholAmount,AlcoholpercentOfDailyNeed
0,True,True,True,False,1.0,3,633998,Banana Blueberry Pancakes,55.79,45,...,0.40,2.70,0.49,2.44,0.03,2.26,18.11,1.81000,NaN,NaN
1,True,True,False,False,0.0,1,634426,Basil and Orange Confit Compound Butter,15.07,45,...,0.33,2.17,NaN,NaN,NaN,NaN,NaN,12.25669,NaN,NaN
85,True,True,False,False,5.0,1,634798,Beet Slaw,104.01,45,...,0.34,2.27,0.35,1.77,0.03,2.07,37.69,3.77000,NaN,NaN
100,True,True,False,False,7.0,1,635290,Blender Carrot Soup,57.73,45,...,0.68,4.50,0.84,4.19,0.06,3.92,87.36,8.74000,NaN,NaN
107,True,True,True,False,3.0,1,635495,Blueberry Mojito Popsicles,114.86,45,...,0.28,1.87,0.27,1.35,0.02,1.56,16.49,1.65000,1.25,6.96
96,True,True,False,False,4.0,1,636062,Breakfast Porridge,121.34,45,...,0.43,2.89,0.67,3.33,0.10,6.94,103.44,10.34000,NaN,NaN
22,True,True,False,False,16.0,1,636600,Butternut Squash Soup,102.10,45,...,2.37,15.79,3.57,17.83,0.20,13.23,91.18,9.12000,NaN,NaN
147,True,True,True,True,93.0,2,637297,Cauliflower Chickpea Stew,139.28,45,...,2.34,15.58,4.77,23.83,0.45,29.70,141.16,14.12000,NaN,NaN
132,True,True,False,False,16.0,1,637705,Cherries and Yogurt Parfait,277.28,45,...,0.21,1.42,0.63,3.15,0.19,12.82,472.85,47.29000,1.03,5.73
101,True,True,True,False,10.0,103,641227,Dandelion pesto,132.51,45,...,2.26,15.08,0.29,1.47,0.10,6.80,19.65,1.96000,NaN,NaN
33,True,True,True,False,54.0,2,641443,Detox Orange Carrot Juice,104.27,45,...,1.73,11.54,2.65,13.26,0.35,23.48,168.53,16.85000,NaN,NaN
27,True,True,False,False,19.0,2,641962,Easy Eggplant Parmesan,195.51,45,...,3.28,21.85,2.02,10.12,0.10,6.86,156.77,15.68000,NaN,NaN
72,True,True,True,False,49.0,1,642154,"EASY, CUMIN-LENTIL SPREAD",29.56,45,...,3.62,24.15,1.44,7.19,0.24,16.11,32.02,3.20000,NaN,NaN
20,True,True,True,False,20.0,1,642892,Fire Roasted Tomato Chutney,74.69,45,...,0.74,4.96,0.90,4.50,0.06,3.71,34.28,3.43000,NaN,NaN
119,True,True,True,False,30.0,1,643674,Fried Brown Rice,188.92,25,...,1.47,9.77,7.06,35.32,0.42,27.99,140.79,14.08000,NaN,NaN
24,True,True,False,False,6.0,7,645416,Green Beans with Garlic Chips,83.90,45,...,1.87,12.46,1.28,6.42,0.15,10.04,73.38,7.34000,NaN,NaN
149,True,True,True,True,100.0,4,647875,Indian-Style Dill and Turmeric Potato Salad,117.24,30,...,2.03,13.52,0.21,1.05,NaN,NaN,27.96,2.80000,NaN,NaN
106,True,True,True,False,7.0,1,648467,Japanese Cucumber Salad,29.96,45,...,NaN,NaN,0.24,1.20,0.03,1.80,19.32,1.93000,NaN,NaN
29,True,True,True,False,19.0,1,648742,Kappa Maki,72.94,45,...,NaN,NaN,2.03,10.15,0.19,12.73,21.56,2.16000,NaN,NaN
139,True,True,False,False,37.0,1,649354,Layered Greek Salad,123.12,45,...,0.54,3.62,0.76,3.79,0.14,9.32,286.72,28.67000,NaN,NaN
80,True,True,False,True,61.0,1,650484,Luscious Palak Paneer,557.85,30,...,9.28,61.85,1.77,8.87,0.19,12.85,751.79,75.18000,NaN,NaN
131,True,True,False,False,7.0,1,650772,Mango Cranberry Sherbet,144.10,45,...,1.24,8.26,0.85,4.24,0.10,6.53,163.17,16.32000,NaN,NaN
15,True,True,False,False,8.0,1,653399,Nutty Rice,99.58,45,...,0.43,2.87,2.91,14.54,0.23,15.26,46.57,4.66000,NaN,NaN
42,True,True,False,False,2.0,8,655098,Peach Coconut Ice Cream,72.45,45,...,0.60,4.03,0.97,4.84,0.04,2.41,32.64,3.26000,NaN,NaN
97,True,True,True,False,2.0,1,655282,Peanut Butter Cookies with Flax Seeds and Choc...,18.14,45,...,1.01,6.75,1.54,7.68,0.04,2.57,12.88,1.29000,NaN,NaN
37,True,True,False,False,17.0,1,658495,Roasted Asparagus with Egg Salad,217.78,45,...,2.79,18.61,2.17,10.85,0.23,15.32,150.39,15.04000,NaN,NaN
93,True,True,True,False,4.0,2,658665,Roasted Strawberry Coconut Milk Ice Cream,143.71,45,...,0.16,1.10,0.83,4.14,0.03,2.32,26.76,2.68000,NaN,NaN
148,True,True,False,False,5.0,1,659412,Sautéed Balsamic Green Beans With Cherry Tomatoes,101.81,45,...,0.95,6.35,1.15,5.73,0.12,7.85,55.64,5.56000,NaN,NaN
57,True,True,False,False,5.0,1,659412,Sautéed Balsamic Green Beans With Cherry Tomatoes,101.81,45,...,0.95,6.35,1.15,5.73,0.12,7.85,55.64,5.56000,NaN,NaN
123,True,True,True,True,100.0,1,659689,Seasonal Autumn Stew,172.76,45,...,5.27,35.15,6.15,30.77,0.38,25.44,213.53,21.35000,NaN,NaN
14,True,True,True,False,16.0,2,661036,Spicy Carrot Amaranth Soup,220.53,45,...,1.68,11.20,1.19,5.94,0.09,5.91,103.27,10.33000,NaN,NaN
143,True,True,True,False,50.0,6,661653,Stir Fried Cabbage and Tomatoes,80.89,45,...,1.13,7.54,1.40,7.02,0.19,12.73,110.71,11.07000,NaN,NaN
133,True,True,True,False,7.0,6,663313,The Pearhattan Cocktail,509.89,45,...,0.89,5.91,1.09,5.44,0.10,6.92,63.01,6.30000,21.31,118.40
69,True,True,True,False,11.0,0,673436,Chicken with Avocado Peach Salsa,90.20,45,...,1.62,10.77,1.61,8.04,0.06,3.75,14.21,1.42000,NaN,NaN
31,True,True,False,False,5.0,249,716421,Grilled Peach Melba with Vanilla Bean Frozen Y...,405.52,45,...,1.06,7.08,1.33,6.63,0.07,4.70,184.10,18.41000,NaN,NaN
61,True,True,True,False,13.0,1,1095692,Ginger Melon Side Salad,219.70,10,...,2.10,14.01,1.60,8.02,0.15,9.86,31.29,3.13000,NaN,NaN
102,True,True,True,False,1.0,1,1095713,Coconut Flour Muffins,30.66,45,...,1.57,10.44,NaN,NaN,NaN,NaN,NaN,12.25669,NaN,NaN
129,True,True,True,False,14.0,1,1096178,"Blueberry, Persimmon Smoothie with Banana and ...",48.70,5,...,1.75,11.67,2.97,14.85,0.06,3.78,59.51,5.95000,NaN,NaN
126,True,True,True,False,21.0,1,1096231,Slow Cooker Healthy Sweet Potato Soup with Coc...,418.08,275,...,0.89,5.91,2.00,9.99,0.26,17.24,104.01,10.40000,NaN,NaN
134,True,True,True,True,77.0,1,1096268,Garlic-Roasted Brussels Sprouts Side Dish,170.34,35,...,4.40,29.33,1.23,6.13,0.23,15.57,83.41,8.34000,NaN,NaN
30,True,True,True,False,17.0,1,1096306,Vegan Chana Masala Curry,165.89,30,...,3.34,22.26,2.14,10.71,0.20,13.09,154.27,15.43000,NaN,NaN
39,True,True,True,False,7.0,6,1098357,Three Ingredient Frozen Pina Colada,214.60,5,...,NaN,NaN,1.05,5.25,0.19,12.66,52.87,5.29000,13.36,74.22

#### How many vegan recipes are there (Vegan = Vegetarian and dairy free)?

In [13]:
mask3 = df_receipe1['dairyFree']

vegan_recipes = pd.DataFrame(df_receipe1[mask1&mask3])
vegan_recipes.shape

(29, 76)

In [14]:
vegan = df_receipe1.groupby(['dairyFree','vegetarian']).count()
vegan

                      glutenFree  veryHealthy  healthScore  aggregateLikes  \
dairyFree vegetarian
False     False               55           55           55              55
          True                37           37           37              37
True      False               29           29           29              29
          True                29           29           29              29

                      id  title  pricePerServing  readyInMinutes  servings  \
dairyFree vegetarian
False     False       55     55               55              55        55
          True        37     37               37              37        37
True      False       29     29               29              29        29
          True        29     29               29              29        29

                      sourceUrl  ...  VitaminEAmount  \
dairyFree vegetarian             ...
False     False              55  ...              49
          True               37  ...              37
True      False              29  ...              27
          True               29  ...              25

                      VitaminEpercentOfDailyNeed  VitaminB3Amount  \
dairyFree vegetarian
False     False                               49               50
          True                                37               34
True      False                               27               27
          True                                25               28

                      VitaminB3percentOfDailyNeed  VitaminB1Amount  \
dairyFree vegetarian
False     False                                50               52
          True                                 34               36
True      False                                27               28
          True                                 28               27

                      VitaminB1percentOfDailyNeed  CalciumAmount  \
dairyFree vegetarian
False     False                                52             53
          True                                 36             34
True      False                                28             28
          True                                 27             27

                      CalciumpercentOfDailyNeed  AlcoholAmount  \
dairyFree vegetarian
False     False                              55              9
          True                               37              5
True      False                              29              4
          True                               29              3

                      AlcoholpercentOfDailyNeed
dairyFree vegetarian
False     False                               9
          True                                5
True      False                               4
          True                                3

[4 rows x 74 columns]

#### Compare the average amount of Vitamin B12 for the vegan and non-vegan recipes. How reliable are the results?

In [15]:
non_vegan=pd.DataFrame(df_receipe1[~mask1&~mask3])
non_vegan.head()

,vegetarian,glutenFree,dairyFree,veryHealthy,healthScore,aggregateLikes,id,title,pricePerServing,readyInMinutes,...,VitaminEAmount,VitaminEpercentOfDailyNeed,VitaminB3Amount,VitaminB3percentOfDailyNeed,VitaminB1Amount,VitaminB1percentOfDailyNeed,CalciumAmount,CalciumpercentOfDailyNeed,AlcoholAmount,AlcoholpercentOfDailyNeed
83,False,False,False,False,5.0,0,45945,Oeufs En Meurette,209.85,328,...,0.84,5.61,1.51,7.56,0.15,10.13,124.54,12.45,NaN,NaN
43,False,False,False,False,44.0,1,622825,Tortilla Burger Loco Vaca,407.86,40,...,4.61,30.71,12.82,64.12,0.35,23.42,281.97,28.20,NaN,NaN
104,False,False,False,False,4.0,1,631769,"Bad Boy"" Giant Double Chocolate Cookies",44.08,45,...,0.53,3.52,1.73,8.63,0.20,13.42,64.05,6.41,NaN,NaN
52,False,False,False,False,2.0,16,632101,Almond Butter and Chocolate Squares,92.26,45,...,3.98,26.52,0.81,4.04,0.04,2.51,86.99,8.70,NaN,NaN
21,False,False,False,False,21.0,18,632874,Asian Salmon Burgers With Tangy Ginger Lime Sauce,370.04,30,...,0.81,5.40,11.22,56.10,0.54,36.17,102.05,10.20,NaN,NaN

In [16]:
vegan_recipes['VitaminB12Amount'].mean()

0.24333333333333332

In [17]:
non_vegan['VitaminB12Amount'].mean()

1.3282978723404255

#### Compare the average health Score for both types of recipes (vegan vs non-vegan).

In [18]:
vegan_recipes['healthScore'].mean()

27.724137931034484

In [19]:
non_vegan['healthScore'].mean()

19.945454545454545

#### Create a new column: "VeganWeek" where you decrease the price of vegan products by 10%, but only if they already cost more than 100.

In [20]:
df_receipe1['VeganWeek']=df_receipe1['pricePerServing']

In [21]:
df_receipe1['VeganWeek'][mask1 & mask3]*=0.9
df_receipe1.head()

C:\Users\pralo\AppData\Local\Temp/ipykernel_53220/2198529351.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_receipe1['VeganWeek'][mask1 & mask3]*=0.9

,vegetarian,glutenFree,dairyFree,veryHealthy,healthScore,aggregateLikes,id,title,pricePerServing,readyInMinutes,...,VitaminEpercentOfDailyNeed,VitaminB3Amount,VitaminB3percentOfDailyNeed,VitaminB1Amount,VitaminB1percentOfDailyNeed,CalciumAmount,CalciumpercentOfDailyNeed,AlcoholAmount,AlcoholpercentOfDailyNeed,VeganWeek
83,False,False,False,False,5.0,0,45945,Oeufs En Meurette,209.85,328,...,5.61,1.51,7.56,0.15,10.13,124.54,12.45,NaN,NaN,209.85
43,False,False,False,False,44.0,1,622825,Tortilla Burger Loco Vaca,407.86,40,...,30.71,12.82,64.12,0.35,23.42,281.97,28.20,NaN,NaN,407.86
104,False,False,False,False,4.0,1,631769,"Bad Boy"" Giant Double Chocolate Cookies",44.08,45,...,3.52,1.73,8.63,0.20,13.42,64.05,6.41,NaN,NaN,44.08
95,False,True,True,False,9.0,1,632084,Allergy-Free Stuffed Portobello Mushrooms,138.47,45,...,7.19,4.59,22.96,0.09,6.05,28.08,2.81,NaN,NaN,138.47
52,False,False,False,False,2.0,16,632101,Almond Butter and Chocolate Squares,92.26,45,...,26.52,0.81,4.04,0.04,2.51,86.99,8.70,NaN,NaN,92.26

#### Among the non-vegan recipes, find the one requiring most time to prepare. How is it called?

In [22]:
non_vegan.groupby(['title'])['readyInMinutes'].max().sort_values(ascending=False)[:1]

title
Oeufs En Meurette    328
Name: readyInMinutes, dtype: int64