#### Hi! Today you will play with NaN values and another Data Manipulation methods. Let us know if you need help and also if you need more challenges on that :)

#### The dataset that you will use is again recipes.csv. You can either use your own or the one in the subfolder "data". Do not forget to import the necessary libraries!

In [1]:
import pandas as pd
import numpy as np
filename = 'data/recipes.csv'
df = pd.read_csv(filename, index_col = 0)
df

,vegetarian,glutenFree,dairyFree,veryHealthy,healthScore,aggregateLikes,id,title,pricePerServing,readyInMinutes,...,VitaminB3Amount,VitaminB3percentOfDailyNeed,VitaminB1Amount,VitaminB1percentOfDailyNeed,CalciumAmount,CalciumpercentOfDailyNeed,AlcoholAmount,AlcoholpercentOfDailyNeed,CaffeineAmount,CaffeinepercentOfDailyNeed
0,True,True,True,False,1.0,3,633998,Banana Blueberry Pancakes,55.79,45,...,0.49,2.44,0.03,2.26,18.11,1.81,NaN,NaN,NaN,NaN
1,True,True,False,False,0.0,1,634426,Basil and Orange Confit Compound Butter,15.07,45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,False,False,False,False,3.0,1,635085,Black Bottom Banana Bars,78.85,45,...,2.63,13.13,0.32,21.09,100.80,10.08,0.28,1.53,9.89,3.30
3,True,False,True,False,2.0,1,663229,The Best Raw Chocolate Chip Cookies,54.64,45,...,0.65,3.26,0.10,6.47,26.79,2.68,NaN,NaN,NaN,NaN
4,False,True,False,False,31.0,3,651437,Mediterranean Spinach Artichoke Dip,115.26,45,...,0.66,3.29,0.07,4.64,162.84,16.28,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,False,True,True,False,18.0,13,638315,"Chicken Sausage, White Bean and Cabbage Soup",196.23,45,...,0.53,2.67,0.15,10.23,102.67,10.27,NaN,NaN,NaN,NaN
146,True,False,False,False,1.0,2,656248,Pinot Noir Brownies,65.76,45,...,0.21,1.07,0.03,1.68,19.82,1.98,2.48,13.76,10.69,3.56
147,True,True,True,True,93.0,2,637297,Cauliflower Chickpea Stew,139.28,45,...,4.77,23.83,0.45,29.70,141.16,14.12,NaN,NaN,NaN,NaN
148,True,True,False,False,5.0,1,659412,Saut√©ed Balsamic Green Beans With Cherry Tomatoes,101.81,45,...,1.15,5.73,0.12,7.85,55.64,5.56,NaN,NaN,NaN,NaN
149,True,True,True,True,100.0,4,647875,Indian-Style Dill and Turmeric Potato Salad,117.24,30,...,0.21,1.05,NaN,NaN,27.96,2.80,NaN,NaN,NaN,NaN

#### Print the names of Columns that have null values

In [2]:
df.columns[df.isnull().any()].tolist()

['FiberAmount',
 'FiberpercentOfDailyNeed',
 'VitaminB6Amount',
 'VitaminB6percentOfDailyNeed',
 'ManganeseAmount',
 'ManganesepercentOfDailyNeed',
 'SeleniumAmount',
 'SeleniumpercentOfDailyNeed',
 'PotassiumAmount',
 'PotassiumpercentOfDailyNeed',
 'VitaminB2Amount',
 'VitaminB2percentOfDailyNeed',
 'VitaminCAmount',
 'VitaminCpercentOfDailyNeed',
 'PhosphorusAmount',
 'PhosphoruspercentOfDailyNeed',
 'FolateAmount',
 'FolatepercentOfDailyNeed',
 'VitaminB5Amount',
 'VitaminB5percentOfDailyNeed',
 'MagnesiumAmount',
 'MagnesiumpercentOfDailyNeed',
 'IronAmount',
 'IronpercentOfDailyNeed',
 'VitaminKAmount',
 'VitaminKpercentOfDailyNeed',
 'CopperAmount',
 'CopperpercentOfDailyNeed',
 'VitaminAAmount',
 'VitaminApercentOfDailyNeed',
 'VitaminB12Amount',
 'VitaminB12percentOfDailyNeed',
 'VitaminDAmount',
 'VitaminDpercentOfDailyNeed',
 'ZincAmount',
 'ZincpercentOfDailyNeed',
 'VitaminEAmount',
 'VitaminEpercentOfDailyNeed',
 'VitaminB3Amount',
 'VitaminB3percentOfDailyNeed',
 'VitaminB1Amount',
 'VitaminB1percentOfDailyNeed',
 'CalciumAmount',
 'CalciumpercentOfDailyNeed',
 'AlcoholAmount',
 'AlcoholpercentOfDailyNeed',
 'CaffeineAmount',
 'CaffeinepercentOfDailyNeed']

#### Print the recipes with the highest number of aggregateLikes

In [3]:
df_most_liked_recipes = df.groupby('title')['aggregateLikes'].sum().sort_values(ascending = False)
df_most_liked_recipes.idxmax()

'Slow Cooker Spicy Hot Wings'

#### Handle the missing values of ‚Äúcalcium percent of Daily need‚Äù. Sort the resulting DataFrame by id column.

In [79]:
#I don't understand what means Handle the missing values of ‚Äúcalcium percent of Daily need‚Äù
#So I assume find the missing values 
df_missing_values = df.loc[df['CalciumpercentOfDailyNeed'].isna()]

df_missing_values.sort_values(by = ['id'])

,vegetarian,glutenFree,dairyFree,veryHealthy,healthScore,aggregateLikes,id,title,pricePerServing,readyInMinutes,...,VitaminB3percentOfDailyNeed,VitaminB1Amount,VitaminB1percentOfDailyNeed,CalciumAmount,CalciumpercentOfDailyNeed,AlcoholAmount,AlcoholpercentOfDailyNeed,CaffeineAmount,CaffeinepercentOfDailyNeed,VeganWeek
1,True,True,False,False,0.0,1,634426,Basil and Orange Confit Compound Butter,15.07,45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.07
74,True,False,False,False,0.0,1,634816,Beignets,19.00,45,...,NaN,0.02,1.21,NaN,NaN,NaN,NaN,NaN,NaN,19.00
71,False,True,True,False,1.0,1,640351,"Cranberry ""Cupcakes",31.80,45,...,NaN,0.04,2.63,NaN,NaN,NaN,NaN,NaN,NaN,31.80
25,False,False,False,False,0.0,1,654516,Pandan Thumbprint Biscuits,54.26,45,...,2.87,0.06,3.83,NaN,NaN,NaN,NaN,18.48,6.16,54.26
68,True,False,False,False,0.0,1,658823,Rosewater Lavender Shortbread,16.43,45,...,3.10,0.08,5.54,NaN,NaN,NaN,NaN,NaN,NaN,16.43
138,True,False,True,False,12.0,1,662315,"Sundried Tomato,Olive,Rosemary and Thyme Focca...",81.78,45,...,9.99,0.46,30.84,NaN,NaN,NaN,NaN,NaN,NaN,81.78
66,False,True,False,False,1.0,1,663885,Truffle Linguine With Tomatoes and Pancetta,11.09,45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.09
102,True,True,True,False,1.0,1,1095713,Coconut Flour Muffins,30.66,45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.66

#### Delete the columns that have null values == 141

In [90]:
#I dont get this question. Does it mean drop the columns which have 141 null values? 
#Or drop the column that has null values on the 141th row? 

df_141_null_values = df.isnull().count() 

df_col_to_drop = np.where(df.isnull().count() == 141, df.drop(df_141_null_values), axis = 1)
#df_141_null_values

KeyError: '[150 150 150 150 150 150 150 150 150 150 150 150 150 150 150 150 150 150\n 150 150 150 150 150 150 150 150 150 150 150 150 150 150 150 150 150 150\n 150 150 150 150 150 150 150 150 150 150 150 150 150 150 150 150 150 150\n 150 150 150 150 150 150 150 150 150 150 150 150 150 150 150 150 150 150\n 150 150 150 150 150 150 150] not found in axis'

#### Print the title of the recipes that are vegetarian == TRUE and glutenFree == True

In [6]:
df_filtered = df[(df.vegetarian == True) & (df.glutenFree == True)]
df_filtered.title
#df_filtered_recipes

0                              Banana Blueberry Pancakes
1                Basil and Orange Confit Compound Butter
14                            Spicy Carrot Amaranth Soup
15                                            Nutty Rice
20                           Fire Roasted Tomato Chutney
22                                 Butternut Squash Soup
24                         Green Beans with Garlic Chips
27                                Easy Eggplant Parmesan
29                                            Kappa Maki
30                              Vegan Chana Masala Curry
31     Grilled Peach Melba with Vanilla Bean Frozen Y...
33                             Detox Orange Carrot Juice
37                      Roasted Asparagus with Egg Salad
39                   Three Ingredient Frozen Pina Colada
42                               Peach Coconut Ice Cream
57     Saut√©ed Balsamic Green Beans With Cherry Tomatoes
61                              Ginger Melon Side Salad
69                      Chicken with Avocado Peach Salsa
72                             EASY, CUMIN-LENTIL SPREAD
80                                 Luscious Palak Paneer
85                                             Beet Slaw
93             Roasted Strawberry Coconut Milk Ice Cream
96                                    Breakfast Porridge
97     Peanut Butter Cookies with Flax Seeds and Choc...
100                                  Blender Carrot Soup
101                                      Dandelion pesto
102                                Coconut Flour Muffins
106                              Japanese Cucumber Salad
107                           Blueberry Mojito Popsicles
119                                     Fried Brown Rice
123                                 Seasonal Autumn Stew
126    Slow Cooker Healthy Sweet Potato Soup with Coc...
129    Blueberry, Persimmon Smoothie with Banana and ...
131                              Mango Cranberry Sherbet
132                          Cherries and Yogurt Parfait
133                              The Pearhattan Cocktail
134            Garlic-Roasted Brussels Sprouts Side Dish
139                                  Layered Greek Salad
143                      Stir Fried Cabbage and Tomatoes
147                            Cauliflower Chickpea Stew
148    Saut√©ed Balsamic Green Beans With Cherry Tomatoes
149          Indian-Style Dill and Turmeric Potato Salad
Name: title, dtype: object

#### How many vegan recipes are there (Vegan = Vegetarian and dairy free)?

In [7]:
df_filtered = df[(df.vegetarian == True) & (df.dairyFree == True)]
df_filtered
df_filtered.title.value_counts().sum()

29

#### Compare the average amount of Vitamin B12 for the vegan and non-vegan recipes. How reliable are the results?

In [8]:
vitaminB12_vegan_recipes = df[df.vegetarian == True]
vegan_vitaminB12 = vitaminB12_vegan_recipes.VitaminB12Amount.mean() 

vitaminB12_non_vegan_recipes = df[df.vegetarian == False]
non_vegan_vitaminB12 = vitaminB12_non_vegan_recipes.VitaminB12Amount.mean()

print('Avg amount of Vitamin B12 for vegan recipes: ' + str(vegan_vitaminB12))
print('Avg amount of Vitamin B12 for vegan recipes: ' + str(non_vegan_vitaminB12))

Avg amount of Vitamin B12 for vegan recipes: 0.48357142857142854
Avg amount of Vitamin B12 for vegan recipes: 1.235384615384615

In [9]:
#check results' reliability 
#The results are not reliable as there are many missing observations, which could change the mean value. 
a= vitaminB12_non_vegan_recipes.VitaminB12Amount.isnull().count()
b= vitaminB12_vegan_recipes.VitaminB12Amount.isnull().count()
print('missing values of VitaminB12Amount in vegan and non-vegan recipes are ' + str(b) + ' and ' + str(a))

missing values of VitaminB12Amount in vegan and non-vegan recipes are 66 and 84

#### Compare the average health Score for both types of recipes (vegan vs non-vegan).

In [10]:
healthScore_vegan = df[df.vegetarian == True].healthScore.mean()

healthScore_vegan

18.484848484848484

In [11]:
healthScore_non_vegan = df[df.vegetarian == False].healthScore.mean()
healthScore_non_vegan

#So non-vegan dishes are healthier than vegan ones? Woah

22.107142857142858

#### Create a new column: "VeganWeek" where you decrease the price of vegan products by 10%, but only if they already cost more than 100.

In [12]:
df['VeganWeek'] = np.where((df.pricePerServing > 100), (df.pricePerServing)*.9, (df.pricePerServing)*1)
df

,vegetarian,glutenFree,dairyFree,veryHealthy,healthScore,aggregateLikes,id,title,pricePerServing,readyInMinutes,...,VitaminB3percentOfDailyNeed,VitaminB1Amount,VitaminB1percentOfDailyNeed,CalciumAmount,CalciumpercentOfDailyNeed,AlcoholAmount,AlcoholpercentOfDailyNeed,CaffeineAmount,CaffeinepercentOfDailyNeed,VeganWeek
0,True,True,True,False,1.0,3,633998,Banana Blueberry Pancakes,55.79,45,...,2.44,0.03,2.26,18.11,1.81,NaN,NaN,NaN,NaN,55.790
1,True,True,False,False,0.0,1,634426,Basil and Orange Confit Compound Butter,15.07,45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.070
2,False,False,False,False,3.0,1,635085,Black Bottom Banana Bars,78.85,45,...,13.13,0.32,21.09,100.80,10.08,0.28,1.53,9.89,3.30,78.850
3,True,False,True,False,2.0,1,663229,The Best Raw Chocolate Chip Cookies,54.64,45,...,3.26,0.10,6.47,26.79,2.68,NaN,NaN,NaN,NaN,54.640
4,False,True,False,False,31.0,3,651437,Mediterranean Spinach Artichoke Dip,115.26,45,...,3.29,0.07,4.64,162.84,16.28,NaN,NaN,NaN,NaN,103.734
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,False,True,True,False,18.0,13,638315,"Chicken Sausage, White Bean and Cabbage Soup",196.23,45,...,2.67,0.15,10.23,102.67,10.27,NaN,NaN,NaN,NaN,176.607
146,True,False,False,False,1.0,2,656248,Pinot Noir Brownies,65.76,45,...,1.07,0.03,1.68,19.82,1.98,2.48,13.76,10.69,3.56,65.760
147,True,True,True,True,93.0,2,637297,Cauliflower Chickpea Stew,139.28,45,...,23.83,0.45,29.70,141.16,14.12,NaN,NaN,NaN,NaN,125.352
148,True,True,False,False,5.0,1,659412,Saut√©ed Balsamic Green Beans With Cherry Tomatoes,101.81,45,...,5.73,0.12,7.85,55.64,5.56,NaN,NaN,NaN,NaN,91.629
149,True,True,True,True,100.0,4,647875,Indian-Style Dill and Turmeric Potato Salad,117.24,30,...,1.05,NaN,NaN,27.96,2.80,NaN,NaN,NaN,NaN,105.516

#### Among the non-vegan recipes, find the one requiring most time to prepare. How is it called?

In [73]:


df2 = df.loc[(df.vegetarian == False),'title'][df.readyInMinutes == df['readyInMinutes'].max()]

df2
#df_2nd_solution = df.loc[df.vegetarian == False & df.readyInMinutes.max()].sort_values(by='readyInMinutes')['title'].tail(1)

83    Oeufs En Meurette
Name: title, dtype: object