#### Import pandas library using alias pd.

In [2]:
import pandas as pd

#### Load file recipes.csv from the data subfolder and store it in a variable df. Use the first column as index.

In [3]:
df = pd.read_csv("data/Recipes.csv")
df
new_df = pd.read_csv("data/Recipes.csv", index_col=1) ### first column is index 0 :) Remember that indexing starts at 0
new_df

,Unnamed: 0,glutenFree,dairyFree,veryHealthy,healthScore,aggregateLikes,id,title,pricePerServing,readyInMinutes,...,VitaminB3Amount,VitaminB3percentOfDailyNeed,VitaminB1Amount,VitaminB1percentOfDailyNeed,CalciumAmount,CalciumpercentOfDailyNeed,AlcoholAmount,AlcoholpercentOfDailyNeed,CaffeineAmount,CaffeinepercentOfDailyNeed
vegetarian,,,,,,,,,,,,,,,,,,,,,
True,0,True,True,False,1.0,3,633998,Banana Blueberry Pancakes,55.79,45,...,0.49,2.44,0.03,2.26,18.11,1.81,NaN,NaN,NaN,NaN
True,1,True,False,False,0.0,1,634426,Basil and Orange Confit Compound Butter,15.07,45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
False,2,False,False,False,3.0,1,635085,Black Bottom Banana Bars,78.85,45,...,2.63,13.13,0.32,21.09,100.80,10.08,0.28,1.53,9.89,3.30
True,3,False,True,False,2.0,1,663229,The Best Raw Chocolate Chip Cookies,54.64,45,...,0.65,3.26,0.10,6.47,26.79,2.68,NaN,NaN,NaN,NaN
False,4,True,False,False,31.0,3,651437,Mediterranean Spinach Artichoke Dip,115.26,45,...,0.66,3.29,0.07,4.64,162.84,16.28,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
False,145,True,True,False,18.0,13,638315,"Chicken Sausage, White Bean and Cabbage Soup",196.23,45,...,0.53,2.67,0.15,10.23,102.67,10.27,NaN,NaN,NaN,NaN
True,146,False,False,False,1.0,2,656248,Pinot Noir Brownies,65.76,45,...,0.21,1.07,0.03,1.68,19.82,1.98,2.48,13.76,10.69,3.56
True,147,True,True,True,93.0,2,637297,Cauliflower Chickpea Stew,139.28,45,...,4.77,23.83,0.45,29.70,141.16,14.12,NaN,NaN,NaN,NaN
True,148,True,False,False,5.0,1,659412,Saut√©ed Balsamic Green Beans With Cherry Tomatoes,101.81,45,...,1.15,5.73,0.12,7.85,55.64,5.56,NaN,NaN,NaN,NaN
True,149,True,True,True,100.0,4,647875,Indian-Style Dill and Turmeric Potato Salad,117.24,30,...,0.21,1.05,NaN,NaN,27.96,2.80,NaN,NaN,NaN,NaN

#### Print the type of variable df.

In [4]:
type(new_df)

pandas.core.frame.DataFrame

#### Print the number of columns and number of rows of the df DataFrame.

In [5]:
new_df.shape

(150, 78)

#### What are the names of the columns in df?

In [6]:
new_df.columns

Index(['Unnamed: 0', 'glutenFree', 'dairyFree', 'veryHealthy', 'healthScore',
       'aggregateLikes', 'id', 'title', 'pricePerServing', 'readyInMinutes',
       'servings', 'sourceUrl', 'CaloriesAmount', 'CaloriespercentOfDailyNeed',
       'FatAmount', 'FatpercentOfDailyNeed', 'SaturatedFatAmount',
       'SaturatedFatpercentOfDailyNeed', 'CarbohydratesAmount',
       'CarbohydratespercentOfDailyNeed', 'NetCarbohydratesAmount',
       'NetCarbohydratespercentOfDailyNeed', 'SugarAmount',
       'SugarpercentOfDailyNeed', 'CholesterolAmount',
       'CholesterolpercentOfDailyNeed', 'SodiumAmount',
       'SodiumpercentOfDailyNeed', 'ProteinAmount',
       'ProteinpercentOfDailyNeed', 'FiberAmount', 'FiberpercentOfDailyNeed',
       'VitaminB6Amount', 'VitaminB6percentOfDailyNeed', 'ManganeseAmount',
       'ManganesepercentOfDailyNeed', 'SeleniumAmount',
       'SeleniumpercentOfDailyNeed', 'PotassiumAmount',
       'PotassiumpercentOfDailyNeed', 'VitaminB2Amount',
       'VitaminB2percentOfDailyNeed', 'VitaminCAmount',
       'VitaminCpercentOfDailyNeed', 'PhosphorusAmount',
       'PhosphoruspercentOfDailyNeed', 'FolateAmount',
       'FolatepercentOfDailyNeed', 'VitaminB5Amount',
       'VitaminB5percentOfDailyNeed', 'MagnesiumAmount',
       'MagnesiumpercentOfDailyNeed', 'IronAmount', 'IronpercentOfDailyNeed',
       'VitaminKAmount', 'VitaminKpercentOfDailyNeed', 'CopperAmount',
       'CopperpercentOfDailyNeed', 'VitaminAAmount',
       'VitaminApercentOfDailyNeed', 'VitaminB12Amount',
       'VitaminB12percentOfDailyNeed', 'VitaminDAmount',
       'VitaminDpercentOfDailyNeed', 'ZincAmount', 'ZincpercentOfDailyNeed',
       'VitaminEAmount', 'VitaminEpercentOfDailyNeed', 'VitaminB3Amount',
       'VitaminB3percentOfDailyNeed', 'VitaminB1Amount',
       'VitaminB1percentOfDailyNeed', 'CalciumAmount',
       'CalciumpercentOfDailyNeed', 'AlcoholAmount',
       'AlcoholpercentOfDailyNeed', 'CaffeineAmount',
       'CaffeinepercentOfDailyNeed'],
      dtype='object')

#### Rename column id to RecipeId. Drop column "veryHealthy".

In [33]:
new_df.rename(columns = {'column':'RecipeId'}, inplace = True) ### here you are renaming a column called "column" into "RecipeId" instead of renaming "Id"
new_df

,Unnamed: 0,glutenFree,dairyFree,veryHealthy,healthScore,aggregateLikes,id,title,pricePerServing,readyInMinutes,...,VitaminB3Amount,VitaminB3percentOfDailyNeed,VitaminB1Amount,VitaminB1percentOfDailyNeed,CalciumAmount,CalciumpercentOfDailyNeed,AlcoholAmount,AlcoholpercentOfDailyNeed,CaffeineAmount,CaffeinepercentOfDailyNeed
vegetarian,,,,,,,,,,,,,,,,,,,,,
True,0,True,True,False,1.0,3,633998,Banana Blueberry Pancakes,55.79,45,...,0.49,2.44,0.03,2.26,18.11,1.81,NaN,NaN,NaN,NaN
True,1,True,False,False,0.0,1,634426,Basil and Orange Confit Compound Butter,15.07,45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
False,2,False,False,False,3.0,1,635085,Black Bottom Banana Bars,78.85,45,...,2.63,13.13,0.32,21.09,100.80,10.08,0.28,1.53,9.89,3.30
True,3,False,True,False,2.0,1,663229,The Best Raw Chocolate Chip Cookies,54.64,45,...,0.65,3.26,0.10,6.47,26.79,2.68,NaN,NaN,NaN,NaN
False,4,True,False,False,31.0,3,651437,Mediterranean Spinach Artichoke Dip,115.26,45,...,0.66,3.29,0.07,4.64,162.84,16.28,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
False,145,True,True,False,18.0,13,638315,"Chicken Sausage, White Bean and Cabbage Soup",196.23,45,...,0.53,2.67,0.15,10.23,102.67,10.27,NaN,NaN,NaN,NaN
True,146,False,False,False,1.0,2,656248,Pinot Noir Brownies,65.76,45,...,0.21,1.07,0.03,1.68,19.82,1.98,2.48,13.76,10.69,3.56
True,147,True,True,True,93.0,2,637297,Cauliflower Chickpea Stew,139.28,45,...,4.77,23.83,0.45,29.70,141.16,14.12,NaN,NaN,NaN,NaN
True,148,True,False,False,5.0,1,659412,Saut√©ed Balsamic Green Beans With Cherry Tomatoes,101.81,45,...,1.15,5.73,0.12,7.85,55.64,5.56,NaN,NaN,NaN,NaN
True,149,True,True,True,100.0,4,647875,Indian-Style Dill and Turmeric Potato Salad,117.24,30,...,0.21,1.05,NaN,NaN,27.96,2.80,NaN,NaN,NaN,NaN

In [35]:
new_df.drop("veryHealthy", axis=1, inplace=True) ### the error at the last line says "['veryHealthy'] not found in axis"  That means your axis argument is probably wrong. Did you try another axis?
newdf

KeyError: "['veryHealthy'] not found in axis"

#### Some questions to think of for yourself. Feel free to ask us if you are in doubt, we are open for a discussion! :)

1. Are there any other columns in this dataset that you would consider a candidate for the index column? Why isn't is always a good idea to use a string as index?
2. Take a closer look at arguments "axis" and "inplace" in functions drop(...) and rename(...). Maybe google for documentation if you are not sure what they mean.
        What happens if you wanted to rename a column that is not there?
        What happens if you set the argument inplace=True?

#### Import pandas library using alias pd.

In [7]:
import pandas as pd

#### Load file recipes.csv from the data subfolder and store it in a variable df_ex1. Use the first column as index.

In [8]:
df = pd.read_csv("data/Recipes.csv")
df
df_ex1 = pd.read_csv("data/Recipes.csv", index_col=1) ### same indexing issue :)
df_ex1

,Unnamed: 0,glutenFree,dairyFree,veryHealthy,healthScore,aggregateLikes,id,title,pricePerServing,readyInMinutes,...,VitaminB3Amount,VitaminB3percentOfDailyNeed,VitaminB1Amount,VitaminB1percentOfDailyNeed,CalciumAmount,CalciumpercentOfDailyNeed,AlcoholAmount,AlcoholpercentOfDailyNeed,CaffeineAmount,CaffeinepercentOfDailyNeed
vegetarian,,,,,,,,,,,,,,,,,,,,,
True,0,True,True,False,1.0,3,633998,Banana Blueberry Pancakes,55.79,45,...,0.49,2.44,0.03,2.26,18.11,1.81,NaN,NaN,NaN,NaN
True,1,True,False,False,0.0,1,634426,Basil and Orange Confit Compound Butter,15.07,45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
False,2,False,False,False,3.0,1,635085,Black Bottom Banana Bars,78.85,45,...,2.63,13.13,0.32,21.09,100.80,10.08,0.28,1.53,9.89,3.30
True,3,False,True,False,2.0,1,663229,The Best Raw Chocolate Chip Cookies,54.64,45,...,0.65,3.26,0.10,6.47,26.79,2.68,NaN,NaN,NaN,NaN
False,4,True,False,False,31.0,3,651437,Mediterranean Spinach Artichoke Dip,115.26,45,...,0.66,3.29,0.07,4.64,162.84,16.28,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
False,145,True,True,False,18.0,13,638315,"Chicken Sausage, White Bean and Cabbage Soup",196.23,45,...,0.53,2.67,0.15,10.23,102.67,10.27,NaN,NaN,NaN,NaN
True,146,False,False,False,1.0,2,656248,Pinot Noir Brownies,65.76,45,...,0.21,1.07,0.03,1.68,19.82,1.98,2.48,13.76,10.69,3.56
True,147,True,True,True,93.0,2,637297,Cauliflower Chickpea Stew,139.28,45,...,4.77,23.83,0.45,29.70,141.16,14.12,NaN,NaN,NaN,NaN
True,148,True,False,False,5.0,1,659412,Saut√©ed Balsamic Green Beans With Cherry Tomatoes,101.81,45,...,1.15,5.73,0.12,7.85,55.64,5.56,NaN,NaN,NaN,NaN
True,149,True,True,True,100.0,4,647875,Indian-Style Dill and Turmeric Potato Salad,117.24,30,...,0.21,1.05,NaN,NaN,27.96,2.80,NaN,NaN,NaN,NaN

In [9]:
df_ex1.rename(columns = {'Unnamed: 0':'name'}, inplace = True) ### it was unnamed because it was supposed to be the index :) 
df_ex1 #changed the name for the unnamed as 0 was confusing

,name,glutenFree,dairyFree,veryHealthy,healthScore,aggregateLikes,id,title,pricePerServing,readyInMinutes,...,VitaminB3Amount,VitaminB3percentOfDailyNeed,VitaminB1Amount,VitaminB1percentOfDailyNeed,CalciumAmount,CalciumpercentOfDailyNeed,AlcoholAmount,AlcoholpercentOfDailyNeed,CaffeineAmount,CaffeinepercentOfDailyNeed
vegetarian,,,,,,,,,,,,,,,,,,,,,
True,0,True,True,False,1.0,3,633998,Banana Blueberry Pancakes,55.79,45,...,0.49,2.44,0.03,2.26,18.11,1.81,NaN,NaN,NaN,NaN
True,1,True,False,False,0.0,1,634426,Basil and Orange Confit Compound Butter,15.07,45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
False,2,False,False,False,3.0,1,635085,Black Bottom Banana Bars,78.85,45,...,2.63,13.13,0.32,21.09,100.80,10.08,0.28,1.53,9.89,3.30
True,3,False,True,False,2.0,1,663229,The Best Raw Chocolate Chip Cookies,54.64,45,...,0.65,3.26,0.10,6.47,26.79,2.68,NaN,NaN,NaN,NaN
False,4,True,False,False,31.0,3,651437,Mediterranean Spinach Artichoke Dip,115.26,45,...,0.66,3.29,0.07,4.64,162.84,16.28,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
False,145,True,True,False,18.0,13,638315,"Chicken Sausage, White Bean and Cabbage Soup",196.23,45,...,0.53,2.67,0.15,10.23,102.67,10.27,NaN,NaN,NaN,NaN
True,146,False,False,False,1.0,2,656248,Pinot Noir Brownies,65.76,45,...,0.21,1.07,0.03,1.68,19.82,1.98,2.48,13.76,10.69,3.56
True,147,True,True,True,93.0,2,637297,Cauliflower Chickpea Stew,139.28,45,...,4.77,23.83,0.45,29.70,141.16,14.12,NaN,NaN,NaN,NaN
True,148,True,False,False,5.0,1,659412,Saut√©ed Balsamic Green Beans With Cherry Tomatoes,101.81,45,...,1.15,5.73,0.12,7.85,55.64,5.56,NaN,NaN,NaN,NaN
True,149,True,True,True,100.0,4,647875,Indian-Style Dill and Turmeric Potato Salad,117.24,30,...,0.21,1.05,NaN,NaN,27.96,2.80,NaN,NaN,NaN,NaN

#### See if the 34th recipe on the list is vegetarian (remember the 0-based indexing!). Please do this in 4 different ways. Be careful with how .iloc and .loc handle things.

In [10]:
df_ex1.iloc[33, 7] #i dont understand how to reach column "vegetarian". when i put 0 instead of 8, it refers to the name.

### That's because you used the vegetarian column as an index. You can't access an index like a normal cell in the table.
### If you use the right index, this will be easier :)

'Detox Orange Carrot Juice'

In [3]:
df_ex1['title'][0] #why does it go through the whole df and does not choose the raw i asked to choose?


### That's because your index is not numbers. If you check the table above, you see the first column being the index column which is "vegetarian"
### That means your index is "True" and "False" values, which is not a good index to have. 
### I can see most of your issues with the exercises are due to you choosing the wrong index column :)

NameError: name 'df_ex1' is not defined

#### Choose columns with the following info and in the following order: title, price and if it is vegetarian

In [15]:
df_ex1[['title', 'pricePerServing']] #i did not put vege but it is still there

### again, it's because you used the vegetarian as your index. Index will always show

                                                        title  pricePerServing
vegetarian
True                                Banana Blueberry Pancakes            55.79
True                  Basil and Orange Confit Compound Butter            15.07
False                                Black Bottom Banana Bars            78.85
True                      The Best Raw Chocolate Chip Cookies            54.64
False                     Mediterranean Spinach Artichoke Dip           115.26
...                                                       ...              ...
False            Chicken Sausage, White Bean and Cabbage Soup           196.23
True                                      Pinot Noir Brownies            65.76
True                                Cauliflower Chickpea Stew           139.28
True        Saut√©ed Balsamic Green Beans With Cherry Tomatoes           101.81
True              Indian-Style Dill and Turmeric Potato Salad           117.24

[150 rows x 2 columns]

#### And now the same for recipes number from 24 to 29

In [16]:
df_ex1.iloc[24 : 30, 7 : 9]

                                    title  pricePerServing
vegetarian
True        Green Beans with Garlic Chips            83.90
False          Pandan Thumbprint Biscuits            54.26
False                       Lamb Moussaka           528.50
True               Easy Eggplant Parmesan           195.51
True                            Peach Pie           173.52
True                           Kappa Maki            72.94

#### Play with some slicing and accesing. Do you understand the result that you obtain from different trials? Please feel free to ask us about what you see! :)

In [57]:
df_ex1.iloc[[1, 2, 3],:]

,name,glutenFree,dairyFree,veryHealthy,healthScore,aggregateLikes,id,title,pricePerServing,readyInMinutes,...,VitaminB3Amount,VitaminB3percentOfDailyNeed,VitaminB1Amount,VitaminB1percentOfDailyNeed,CalciumAmount,CalciumpercentOfDailyNeed,AlcoholAmount,AlcoholpercentOfDailyNeed,CaffeineAmount,CaffeinepercentOfDailyNeed
vegetarian,,,,,,,,,,,,,,,,,,,,,
True,1,True,False,False,0.0,1,634426,Basil and Orange Confit Compound Butter,15.07,45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
False,2,False,False,False,3.0,1,635085,Black Bottom Banana Bars,78.85,45,...,2.63,13.13,0.32,21.09,100.80,10.08,0.28,1.53,9.89,3.3
True,3,False,True,False,2.0,1,663229,The Best Raw Chocolate Chip Cookies,54.64,45,...,0.65,3.26,0.10,6.47,26.79,2.68,NaN,NaN,NaN,NaN

#### Notice which slicing methods are inclusive and which of them are exclusive. Try to figure your favourite way of accesing / slicing and remember that sometimes some of them make more sense than the others.

In [42]:
df_ex1[20:40] #raws

,name,glutenFree,dairyFree,veryHealthy,healthScore,aggregateLikes,id,title,pricePerServing,readyInMinutes,...,VitaminB3Amount,VitaminB3percentOfDailyNeed,VitaminB1Amount,VitaminB1percentOfDailyNeed,CalciumAmount,CalciumpercentOfDailyNeed,AlcoholAmount,AlcoholpercentOfDailyNeed,CaffeineAmount,CaffeinepercentOfDailyNeed
vegetarian,,,,,,,,,,,,,,,,,,,,,
True,20,True,True,False,20.0,1,642892,Fire Roasted Tomato Chutney,74.69,45,...,0.90,4.50,0.06,3.71,34.28,3.43,NaN,NaN,NaN,NaN
False,21,False,False,False,21.0,18,632874,Asian Salmon Burgers With Tangy Ginger Lime Sauce,370.04,30,...,11.22,56.10,0.54,36.17,102.05,10.20,NaN,NaN,NaN,NaN
True,22,True,False,False,16.0,1,636600,Butternut Squash Soup,102.10,45,...,3.57,17.83,0.20,13.23,91.18,9.12,NaN,NaN,NaN,NaN
True,23,False,False,False,9.0,1,635447,Blueberry Compote Bread Pudding With Soft Curd...,270.38,45,...,0.59,2.97,0.27,18.00,613.26,61.33,NaN,NaN,NaN,NaN
True,24,True,False,False,6.0,7,645416,Green Beans with Garlic Chips,83.90,45,...,1.28,6.42,0.15,10.04,73.38,7.34,NaN,NaN,NaN,NaN
False,25,False,False,False,0.0,1,654516,Pandan Thumbprint Biscuits,54.26,45,...,0.57,2.87,0.06,3.83,NaN,NaN,NaN,NaN,18.48,6.16
False,26,False,False,False,42.0,1,649225,Lamb Moussaka,528.50,45,...,30.58,152.90,0.46,30.62,478.31,47.83,1.05,5.83,NaN,NaN
True,27,True,False,False,19.0,2,641962,Easy Eggplant Parmesan,195.51,45,...,2.02,10.12,0.10,6.86,156.77,15.68,NaN,NaN,NaN,NaN
True,28,False,False,False,3.0,7,655145,Peach Pie,173.52,45,...,1.68,8.41,0.16,10.93,116.78,11.68,0.75,4.14,NaN,NaN
True,29,True,True,False,19.0,1,648742,Kappa Maki,72.94,45,...,2.03,10.15,0.19,12.73,21.56,2.16,NaN,NaN,NaN,NaN
True,30,True,True,False,17.0,1,1096306,Vegan Chana Masala Curry,165.89,30,...,2.14,10.71,0.20,13.09,154.27,15.43,NaN,NaN,NaN,NaN
True,31,True,False,False,5.0,249,716421,Grilled Peach Melba with Vanilla Bean Frozen Y...,405.52,45,...,1.33,6.63,0.07,4.70,184.10,18.41,NaN,NaN,NaN,NaN
False,32,True,True,False,6.0,1,652758,Mussels Marinara,125.90,45,...,0.90,4.52,0.06,4.19,41.74,4.17,6.18,34.33,NaN,NaN
True,33,True,True,False,54.0,2,641443,Detox Orange Carrot Juice,104.27,45,...,2.65,13.26,0.35,23.48,168.53,16.85,NaN,NaN,NaN,NaN
False,34,True,False,True,78.0,15,661340,Spinach Salad with Strawberry Vinaigrette,338.97,45,...,6.03,30.15,0.19,12.65,221.46,22.15,NaN,NaN,NaN,NaN
False,35,True,False,False,9.0,6,634605,Beef Cottage Pie,113.45,45,...,3.31,16.55,0.05,3.33,45.50,4.55,NaN,NaN,NaN,NaN
False,36,False,False,True,57.0,1,647124,Homemade Thin Crust Pizza + Pesto + Potato,199.57,45,...,7.12,35.59,1.12,74.83,201.23,20.12,NaN,NaN,NaN,NaN
True,37,True,False,False,17.0,1,658495,Roasted Asparagus with Egg Salad,217.78,45,...,2.17,10.85,0.23,15.32,150.39,15.04,NaN,NaN,NaN,NaN
True,38,False,False,False,9.0,1,649300,Latkes; Fried Vegetable Pancakes from Europe a...,58.55,45,...,2.20,10.98,0.27,17.86,56.43,5.64,NaN,NaN,NaN,NaN
True,39,True,True,False,7.0,6,1098357,Three Ingredient Frozen Pina Colada,214.60,5,...,1.05,5.25,0.19,12.66,52.87,5.29,13.36,74.22,NaN,NaN

### Class-exercise 2

In [99]:
import numpy as np

1. Create a 2-d and 3-d numpy integer array

In [100]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 10, 20]) 
b = np.array([[1, 2, 3], [5, 10, 20]]) #how many elements can be in each [] brackets? 
### As many as you want as long as the dimensions make sense as a matrix

print(a.ndim) 
print(b.ndim)
print(c.ndim)

1
2
2

2. Create a 2X2 integer array and show it's dimensions

In [98]:
b = np.array([[1, 2], [5, 10]])
print(b.ndim)

2

3. Create a numpy array and  print the sum of third and fourth elements from the array

In [106]:
a = np.array([1, 2, 3, 4, 5, 10, 20])
print(a[2] + a[3])

7

In [113]:
b = np.array([[1, 2], [5, 10]])
print(b[0, 1] + b[1, 1])

12

4. Slice the below array to get the the second item to the excluding fifth item

arr = np.array([10, 15, 20, 25, 30, 35, 40])

In [117]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])
print(arr[1:5])

[15 20 25 30]

5. Try example 4. using STEP method

In [119]:
print(arr[1:5:1])

[15 20 25 30]

6. Create a integer array and change data type from integer to boolean

In [124]:
cat = np.array([0,1,0,1,2,3],dtype=bool)
newar = cat.astype('bool')
print(newar.dtype)

bool

7. Use NumPy syntax to check the shape of an array.

arr = np.array([1, 2, 3, 4, 5])

In [128]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.shape)

(5,)

8. Find the indexes where the values are even:

arr = [16, 8, 3, 7, 15, 24]

In [163]:
arr = np.array([16, 8, 3, 7, 15, 24])
x = np.where(arr%2 == 0)
print(x)

### Do you understand the result here? You got the indices of the items you asked for

(array([0, 1, 5], dtype=int64),)

9. Create a numpy array of 5 person names and sort the values alpbabetically

In [144]:
cat = np.array(['victoria', 'radhika', 'leo', 'rami', 'edit' ],dtype='S')
print(np.sort(cat)) #what is b?

### b is due to some encoding stuff. Try setting dtype to 'U' and see if it makes a difference. Read about type U too

[b'edit' b'leo' b'radhika' b'rami' b'victoria']

10. Use the correct NumPy method to return a sorted array.

  arr = np.array([3, 2, 0, 1])

In [145]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]